import { Level } from "@prisma/client";
import type { VocabEntry } from "./types";

/** Real C1 (advanced) English vocabulary — only entries not already in other seeds. */
export const advancedC1Vocab: VocabEntry[] = [
  { word: "aberration", meaning: "a departure from what is normal", meaningKh: "ភាពមិនធម្មតា", example: "The election result was an aberration.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "abolish", meaning: "to formally put an end to", meaningKh: "លុបបំបាត់", example: "The new law abolished slavery.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "abrupt", meaning: "sudden and unexpected", meaningKh: "ភ្លាមៗ", example: "The meeting came to an abrupt end.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "accelerate", meaning: "to increase in speed", meaningKh: "បង្កើនល្បឿន", example: "The car accelerated quickly.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "accessible", meaning: "easy to reach or use", meaningKh: "ងាយចូលដល់", example: "The website is accessible to everyone.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "accommodate", meaning: "to provide room or adapt to", meaningKh: "ផ្តល់កន្លែង", example: "The hotel can accommodate 200 guests.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "accumulate", meaning: "to gather over time", meaningKh: "ប្រមូលផ្តុំ", example: "Dust accumulates quickly.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "adjacent", meaning: "next to or adjoining", meaningKh: "ជាប់គ្នា", example: "Our offices are adjacent.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "administer", meaning: "to manage or give out officially", meaningKh: "គ្រប់គ្រង", example: "She administers the company's budget.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "adolescent", meaning: "a teenager", meaningKh: "ក្មេងជំទង់", example: "Adolescents need plenty of sleep.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "advocate", meaning: "to publicly support something", meaningKh: "តស៊ូមតិ", example: "She advocates for human rights.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "aesthetic", meaning: "relating to beauty", meaningKh: "សោភ័ណភាព", example: "The room has a modern aesthetic.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "aggregate", meaning: "a whole formed from parts", meaningKh: "សរុប", example: "Their aggregate score was highest.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "albeit", meaning: "even though", meaningKh: "ទោះបី", example: "It was a useful meeting, albeit a short one.", partOfSpeech: "conjunction", level: Level.ADVANCED },
  { word: "allocate", meaning: "to assign for a purpose", meaningKh: "បែងចែក", example: "We allocate funds for research.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "alteration", meaning: "a change", meaningKh: "ការផ្លាស់ប្តូរ", example: "The dress needs alterations.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "ambiguous", meaning: "having more than one meaning", meaningKh: "មិនច្បាស់លាស់", example: "His answer was ambiguous.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "amend", meaning: "to change or improve", meaningKh: "កែប្រែ", example: "They amended the contract.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "analogy", meaning: "a comparison between two things", meaningKh: "ការប្រៀបធៀប", example: "He used an analogy to explain.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "analytical", meaning: "using logical thinking", meaningKh: "វិភាគ", example: "She has an analytical mind.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "ancestor", meaning: "a person from whom one is descended", meaningKh: "បុព្វបុរស", example: "Her ancestors came from China.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "anticipate", meaning: "to expect or predict", meaningKh: "រំពឹង", example: "We anticipate good results.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "apparent", meaning: "clearly visible or understood", meaningKh: "ច្បាស់ជាក់", example: "It was apparent he was tired.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "appendix", meaning: "extra material at the end of a book", meaningKh: "ឧបសម្ព័ន្ធ", example: "See the appendix for details.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "appetite", meaning: "desire for food", meaningKh: "ចំណង់អាហារ", example: "Exercise increases your appetite.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "applicable", meaning: "relevant; appropriate", meaningKh: "អនុវត្តបាន", example: "This rule isn't applicable here.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "apprehensive", meaning: "anxious; worried", meaningKh: "ភ័យព្រួយ", example: "She was apprehensive about the exam.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "arbitrary", meaning: "based on personal choice; random", meaningKh: "តាមអំពើចិត្ត", example: "The decision seemed arbitrary.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "archive", meaning: "a collection of historical records", meaningKh: "បណ្ណសារ", example: "The library has a music archive.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "argumentative", meaning: "given to arguing", meaningKh: "ចូលចិត្តឈ្លោះ", example: "He's too argumentative.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "articulate", meaning: "able to express ideas clearly", meaningKh: "និយាយច្បាស់", example: "She is articulate and intelligent.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "ascend", meaning: "to go up", meaningKh: "ឡើង", example: "The plane ascended slowly.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "aspiration", meaning: "a strong desire to achieve", meaningKh: "សេចក្តីប្រាថ្នា", example: "She has aspirations of becoming a doctor.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "assault", meaning: "a violent attack", meaningKh: "ការវាយប្រហារ", example: "He was charged with assault.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "assert", meaning: "to state confidently", meaningKh: "អះអាង", example: "She asserted her rights.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "asset", meaning: "something valuable owned", meaningKh: "ទ្រព្យសម្បត្តិ", example: "Her honesty is a great asset.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "astonishing", meaning: "extremely surprising", meaningKh: "គួរឱ្យភ្ញាក់ផ្អើល", example: "The view was astonishing.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "attribute", meaning: "a quality or feature", meaningKh: "លក្ខណៈ", example: "Patience is one of her best attributes.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "authorize", meaning: "to give official permission", meaningKh: "អនុញ្ញាត", example: "Only I can authorize this.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "autonomy", meaning: "self-government; independence", meaningKh: "ស្វ័យភាព", example: "The region has political autonomy.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "awkward", meaning: "uncomfortable; difficult", meaningKh: "ឆ្គង", example: "It was an awkward silence.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "backlash", meaning: "a strong negative reaction", meaningKh: "ប្រតិកម្ម​អវិជ្ជមាន", example: "The new policy caused a backlash.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "beneficial", meaning: "producing good results", meaningKh: "មានប្រយោជន៍", example: "Exercise is beneficial to health.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "bias", meaning: "unfair preference", meaningKh: "ការលំអៀង", example: "The judge showed no bias.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "bizarre", meaning: "very strange or unusual", meaningKh: "ប្លែក", example: "She had a bizarre dream.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "boundary", meaning: "a dividing line", meaningKh: "ព្រំដែន", example: "The river is the boundary.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "briefly", meaning: "for a short time", meaningKh: "យ៉ាងសង្ខេប", example: "He spoke briefly about the issue.", partOfSpeech: "adverb", level: Level.ADVANCED },
  { word: "bulk", meaning: "the largest part; great size", meaningKh: "ភាគច្រើន", example: "Buy in bulk to save money.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "capability", meaning: "the power or ability", meaningKh: "សមត្ថភាព", example: "He has great leadership capability.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "casualty", meaning: "a victim of accident or war", meaningKh: "ជនរងគ្រោះ", example: "There were many casualties in the storm.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "cautious", meaning: "careful to avoid danger", meaningKh: "ប្រុងប្រយ័ត្ន", example: "Be cautious when crossing the street.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "cease", meaning: "to stop", meaningKh: "ឈប់", example: "The rain finally ceased.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "chronic", meaning: "lasting a long time", meaningKh: "រ៉ាំរ៉ៃ", example: "She has chronic pain.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "circulate", meaning: "to move around freely", meaningKh: "ផ្សព្វផ្សាយ", example: "Rumors circulated quickly.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "citation", meaning: "a quote from a source", meaningKh: "ការដកស្រង់", example: "Include citations in your essay.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "civilian", meaning: "a non-military person", meaningKh: "ជនស៊ីវិល", example: "The war hurt many civilians.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "clarify", meaning: "to make clear", meaningKh: "បំភ្លឺ", example: "Can you clarify that point?", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "coherent", meaning: "logical and well-organized", meaningKh: "ស៊ីសង្វាក់គ្នា", example: "She gave a coherent answer.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "coincide", meaning: "to happen at the same time", meaningKh: "កើតឡើងជាមួយគ្នា", example: "Our visits coincided.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "collaborate", meaning: "to work together", meaningKh: "សហការ", example: "Scientists collaborate across countries.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "commence", meaning: "to begin", meaningKh: "ចាប់ផ្តើម", example: "The ceremony will commence at noon.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "commodity", meaning: "a useful or valuable thing", meaningKh: "ទំនិញ", example: "Oil is an important commodity.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "compatible", meaning: "able to exist together", meaningKh: "សមស្រប", example: "These two programs are compatible.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "compensate", meaning: "to make up for", meaningKh: "សងថ្នូរ", example: "We must compensate the victims.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "compile", meaning: "to gather and put together", meaningKh: "ចងក្រង", example: "He compiled a list of names.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "complement", meaning: "to complete or add to", meaningKh: "បំពេញបន្ថែម", example: "The wine complements the meal.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "complexity", meaning: "the state of being complex", meaningKh: "ភាពស្មុគស្មាញ", example: "The complexity of the issue surprised us.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "comprehensive", meaning: "complete; including everything", meaningKh: "ទូលំទូលាយ", example: "We need a comprehensive plan.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "conceive", meaning: "to think of; to imagine", meaningKh: "យល់ឃើញ", example: "I can hardly conceive of such cruelty.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "conceptual", meaning: "based on ideas", meaningKh: "គំនិត", example: "The work is at a conceptual stage.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "concurrent", meaning: "happening at the same time", meaningKh: "ដំណាលគ្នា", example: "He served concurrent sentences.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "configuration", meaning: "the arrangement of parts", meaningKh: "ការកំណត់រចនាសម្ព័ន្ធ", example: "Change the system configuration.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "confine", meaning: "to limit or restrict", meaningKh: "កំណត់", example: "Please confine your remarks to the topic.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "confront", meaning: "to face boldly", meaningKh: "ប្រឈមមុខ", example: "We must confront this problem.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "consecutive", meaning: "following one after another", meaningKh: "បន្តបន្ទាប់", example: "She won three consecutive games.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "consensus", meaning: "general agreement", meaningKh: "មតិឯកភាព", example: "We reached a consensus.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "consent", meaning: "permission; agreement", meaningKh: "ការយល់ព្រម", example: "She gave her consent.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "conserve", meaning: "to use carefully; to protect", meaningKh: "អភិរក្ស", example: "Conserve water during droughts.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "considerable", meaning: "notably large", meaningKh: "ច្រើនគួរសម", example: "It took a considerable amount of time.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "consistent", meaning: "acting the same way", meaningKh: "ស្ថិរភាព", example: "Her work is consistent in quality.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "consolidate", meaning: "to combine or strengthen", meaningKh: "ពង្រឹង", example: "They consolidated their debts.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "constraint", meaning: "a limitation", meaningKh: "ការរឹតបន្តឹង", example: "Budget constraints limited the project.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "contradict", meaning: "to say the opposite", meaningKh: "បដិសេធ", example: "His actions contradict his words.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "controversial", meaning: "causing strong disagreement", meaningKh: "ចម្រូងចម្រាស់", example: "It was a controversial decision.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "conventional", meaning: "based on tradition", meaningKh: "ប្រពៃណី", example: "She has conventional views.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "convert", meaning: "to change into another form", meaningKh: "បំលែង", example: "Convert dollars into riels.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "coordinate", meaning: "to organize together", meaningKh: "សម្របសម្រួល", example: "She coordinates the team's work.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "correspond", meaning: "to match; to communicate", meaningKh: "ត្រូវនឹង", example: "The names don't correspond.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "credible", meaning: "able to be believed", meaningKh: "គួរឱ្យជឿ", example: "Her story isn't credible.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "criteria", meaning: "standards for judging", meaningKh: "លក្ខណៈវិនិច្ឆ័យ", example: "What are the criteria for selection?", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "cultivate", meaning: "to grow; to develop", meaningKh: "បណ្តុះ", example: "He cultivates rice on his land.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "currency", meaning: "money used in a country", meaningKh: "រូបិយវត្ថុ", example: "The riel is Cambodia's currency.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "debris", meaning: "scattered broken pieces", meaningKh: "កំទេចកំទី", example: "Debris from the storm was everywhere.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "decisive", meaning: "able to make decisions quickly", meaningKh: "ដាច់ខាត", example: "She is a decisive leader.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "dedicate", meaning: "to devote", meaningKh: "ឧទ្ទិស", example: "She dedicates time to charity.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "deficiency", meaning: "a lack of something", meaningKh: "ការខ្វះខាត", example: "Vitamin D deficiency is common.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "definite", meaning: "certain; clearly defined", meaningKh: "ច្បាស់លាស់", example: "We need a definite answer.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "delegate", meaning: "to give a task to another", meaningKh: "ប្រគល់សិទ្ធិ", example: "Good managers delegate work.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "deliberate", meaning: "done on purpose", meaningKh: "ដោយចេតនា", example: "It was a deliberate mistake.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "denote", meaning: "to indicate or mean", meaningKh: "មានន័យថា", example: "Red lights denote danger.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "depression", meaning: "deep sadness; an economic slump", meaningKh: "ការធ្លាក់ទឹកចិត្ត", example: "He suffers from depression.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "derive", meaning: "to obtain from a source", meaningKh: "ទាញយក", example: "She derives joy from teaching.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "designate", meaning: "to officially appoint", meaningKh: "កំណត់", example: "He was designated as leader.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "desperate", meaning: "having lost hope; reckless", meaningKh: "អស់សង្ឃឹម", example: "She was desperate for help.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "devastate", meaning: "to destroy or shock deeply", meaningKh: "បំផ្លាញ", example: "The flood devastated the village.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "differentiate", meaning: "to distinguish between", meaningKh: "បែងចែក", example: "Can you differentiate the two?", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "dilemma", meaning: "a difficult choice", meaningKh: "បញ្ហាដ៏លំបាក", example: "She faced a difficult dilemma.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "diminish", meaning: "to become smaller", meaningKh: "ថយចុះ", example: "His influence has diminished.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "discriminate", meaning: "to treat unfairly; to distinguish", meaningKh: "រើសអើង", example: "Companies must not discriminate.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "displace", meaning: "to force from a place", meaningKh: "ផ្លាស់ទីលំនៅ", example: "Thousands were displaced by war.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "dispose", meaning: "to get rid of; to arrange", meaningKh: "បោះចោល", example: "Dispose of the trash properly.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "distinct", meaning: "clearly different", meaningKh: "ខុសគ្នាច្បាស់", example: "Two distinct flavors blend here.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "distort", meaning: "to change from the truth", meaningKh: "បំភ្លៃ", example: "Don't distort my words.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "dominant", meaning: "most powerful or important", meaningKh: "លេចធ្លោ", example: "She is the dominant player.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "duration", meaning: "the length of time", meaningKh: "រយៈពេល", example: "The duration of the trip is two weeks.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "dynamic", meaning: "full of energy", meaningKh: "សកម្ម", example: "She's a dynamic young leader.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "economical", meaning: "not wasteful", meaningKh: "សន្សំសំចៃ", example: "This car is very economical.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "elaborate", meaning: "to add detail", meaningKh: "ពន្យល់លម្អិត", example: "Can you elaborate on that?", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "empirical", meaning: "based on observation", meaningKh: "ផ្អែកលើបទពិសោធន៍", example: "We need empirical evidence.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "entity", meaning: "a thing with a distinct existence", meaningKh: "អង្គភាព", example: "The company is a separate legal entity.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "environmental", meaning: "of the natural surroundings", meaningKh: "បរិស្ថាន", example: "Environmental protection is vital.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "equivalent", meaning: "equal in value or meaning", meaningKh: "សមមូល", example: "One dollar is equivalent to 4000 riels.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "eradicate", meaning: "to completely destroy", meaningKh: "លុបបំបាត់", example: "They aim to eradicate poverty.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "evolve", meaning: "to develop gradually", meaningKh: "វិវឌ្ឍន៍", example: "Species evolve over time.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "exaggerate", meaning: "to overstate", meaningKh: "បំផ្លើស", example: "Don't exaggerate the danger.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "exceptional", meaning: "unusually good or rare", meaningKh: "ពិសេស", example: "She has exceptional talent.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "excessive", meaning: "more than necessary", meaningKh: "ច្រើនលើស", example: "Excessive eating is unhealthy.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "execute", meaning: "to carry out; to put to death", meaningKh: "អនុវត្ត", example: "They executed the plan flawlessly.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "explicit", meaning: "stated clearly", meaningKh: "ច្បាស់លាស់", example: "She gave explicit instructions.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "exploit", meaning: "to use for one's benefit", meaningKh: "កេងប្រវ័ញ្ច", example: "Companies that exploit workers are wrong.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "expose", meaning: "to reveal", meaningKh: "បង្ហាញឱ្យឃើញ", example: "The reporter exposed the scandal.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "extensive", meaning: "covering a large area", meaningKh: "ទូលំទូលាយ", example: "She has extensive experience.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "facilitate", meaning: "to make easier", meaningKh: "សម្រួល", example: "Technology facilitates learning.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "feasible", meaning: "possible; practical", meaningKh: "អាចធ្វើបាន", example: "Is this plan feasible?", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "fluctuate", meaning: "to change frequently", meaningKh: "ប្រែប្រួល", example: "Prices fluctuate daily.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "formulate", meaning: "to create or prepare", meaningKh: "បង្កើតគំនិត", example: "She formulated a new theory.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "fragment", meaning: "a small broken piece", meaningKh: "បំណែក", example: "Fragments of glass were everywhere.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "globalization", meaning: "worldwide integration", meaningKh: "សកលភាវូបនីយកម្ម", example: "Globalization affects every country.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "guideline", meaning: "a general rule or principle", meaningKh: "គោលការណ៍ណែនាំ", example: "Follow the safety guidelines.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "hence", meaning: "as a result; therefore", meaningKh: "ដូច្នេះ", example: "It rained; hence we stayed in.", partOfSpeech: "adverb", level: Level.ADVANCED },
  { word: "hierarchy", meaning: "a system of ranking", meaningKh: "ឋានានុក្រម", example: "Every organization has a hierarchy.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "hypothesis", meaning: "a proposed explanation", meaningKh: "សម្មតិកម្ម", example: "Test the hypothesis carefully.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "identical", meaning: "exactly the same", meaningKh: "ដូចគ្នាបេះបិទ", example: "The twins are identical.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "ideology", meaning: "a system of beliefs", meaningKh: "មនោគមវិជ្ជា", example: "Political ideology divides them.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "immune", meaning: "protected from disease", meaningKh: "មានភាពស៊ាំ", example: "She is immune to the virus.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "implicate", meaning: "to show as involved", meaningKh: "ចោទប្រកាន់", example: "The evidence implicated him.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "implicit", meaning: "suggested but not stated", meaningKh: "ដោយប្រយោល", example: "There was implicit approval.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "impose", meaning: "to force upon", meaningKh: "ដាក់បង្ខំ", example: "The government imposed new taxes.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "incentive", meaning: "a reason to do something", meaningKh: "ការលើកទឹកចិត្ត", example: "Bonuses are good incentives.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "incidence", meaning: "the rate of occurrence", meaningKh: "ឧប្បត្តិហេតុ", example: "The incidence of flu is rising.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "incline", meaning: "to lean; to tend toward", meaningKh: "ទេរទៅ", example: "She inclined her head slightly.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "incorporate", meaning: "to include as part", meaningKh: "បញ្ចូល", example: "We incorporated his ideas.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "infrastructure", meaning: "basic facilities of a society", meaningKh: "ហេដ្ឋារចនាសម្ព័ន្ធ", example: "Roads are part of infrastructure.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "inherent", meaning: "existing as a permanent part", meaningKh: "ដែលមានពីកំណើត", example: "Risk is inherent in any investment.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "inhibit", meaning: "to prevent or slow", meaningKh: "ទប់ស្កាត់", example: "Fear can inhibit progress.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "initially", meaning: "at first", meaningKh: "ដំបូងឡើយ", example: "Initially, I was unsure.", partOfSpeech: "adverb", level: Level.ADVANCED },
  { word: "input", meaning: "what is contributed or entered", meaningKh: "ការបញ្ចូល", example: "We value your input.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "insert", meaning: "to place into", meaningKh: "ដាក់ចូល", example: "Insert the key into the lock.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "integrate", meaning: "to combine into one", meaningKh: "បញ្ចូលគ្នា", example: "They integrate immigrants into society.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "intermediate", meaning: "in the middle stage", meaningKh: "កម្រិតមធ្យម", example: "She is at an intermediate level.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "intrinsic", meaning: "belonging naturally", meaningKh: "ខាងក្នុង", example: "Honesty has intrinsic value.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "justify", meaning: "to show as right", meaningKh: "ដាក់ហេតុផល", example: "How can you justify your actions?", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "knowledgeable", meaning: "well-informed", meaningKh: "មានចំណេះដឹង", example: "She is knowledgeable about wine.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "landmark", meaning: "a recognizable feature; major event", meaningKh: "ចំណុចសម្គាល់", example: "Angkor Wat is a famous landmark.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "legislation", meaning: "laws as a group", meaningKh: "ច្បាប់", example: "New legislation passed today.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "legitimate", meaning: "lawful; valid", meaningKh: "ត្រឹមត្រូវស្របច្បាប់", example: "He has a legitimate claim.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "likewise", meaning: "in the same way", meaningKh: "ដូចគ្នា", example: "I'm tired; likewise, she is too.", partOfSpeech: "adverb", level: Level.ADVANCED },
  { word: "linear", meaning: "in a straight line", meaningKh: "បន្ទាត់", example: "The data shows a linear trend.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "manipulate", meaning: "to handle skillfully; to influence unfairly", meaningKh: "រៀបរៀង", example: "He manipulates people for his gain.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "marginal", meaning: "small; on the edge", meaningKh: "តិចតួច", example: "The change is only marginal.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "maximize", meaning: "to make as great as possible", meaningKh: "បង្កើនអតិបរមា", example: "Maximize your time at work.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "mediate", meaning: "to act as a peacemaker", meaningKh: "សម្រុះសម្រួល", example: "She mediated the dispute.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "methodology", meaning: "a system of methods", meaningKh: "វិធីសាស្ត្រ", example: "Their research methodology is sound.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "microscope", meaning: "an instrument for viewing tiny things", meaningKh: "មីក្រូទស្សន៍", example: "We saw cells through a microscope.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "migrate", meaning: "to move from one place to another", meaningKh: "ធ្វើទេសន្តរប្រវេសន៍", example: "Birds migrate south for winter.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "minimal", meaning: "very small in amount", meaningKh: "តិចតួចបំផុត", example: "The damage was minimal.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "minimize", meaning: "to reduce to the least", meaningKh: "កាត់បន្ថយ", example: "Minimize the risks.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "neutral", meaning: "not taking sides", meaningKh: "អព្យាក្រឹត", example: "She stayed neutral in the argument.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "objective", meaning: "a goal; not biased", meaningKh: "គោលបំណង", example: "Our objective is to win.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "offset", meaning: "to balance against", meaningKh: "ទូទាត់", example: "The losses offset the gains.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "ongoing", meaning: "continuing", meaningKh: "កំពុងបន្ត", example: "It's an ongoing investigation.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "orient", meaning: "to find one's direction", meaningKh: "កំណត់ទិសដៅ", example: "It took time to orient ourselves.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "overlap", meaning: "to extend over a part of", meaningKh: "ត្រួតគ្នា", example: "Our schedules overlap on Tuesday.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "overseas", meaning: "in foreign countries", meaningKh: "នៅបរទេស", example: "She works overseas.", partOfSpeech: "adverb", level: Level.ADVANCED },
  { word: "parallel", meaning: "side by side; similar", meaningKh: "ស្របគ្នា", example: "The two lines are parallel.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "parameter", meaning: "a limit; a measurable factor", meaningKh: "ប៉ារ៉ាម៉ែត្រ", example: "Set the parameters for the test.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "percentile", meaning: "a value below which a percent falls", meaningKh: "ភាគរយចំណាត់ថ្នាក់", example: "She scored in the 90th percentile.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "persistent", meaning: "continuing firmly", meaningKh: "ឧស្សាហ៍", example: "She is persistent in her studies.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "pose", meaning: "to present; to put forth", meaningKh: "ដាក់", example: "This poses a serious problem.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "precede", meaning: "to come before", meaningKh: "មកមុន", example: "A storm preceded the calm.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "predominant", meaning: "most common or important", meaningKh: "លេចធ្លោ", example: "Rice is the predominant food.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "preliminary", meaning: "happening before the main part", meaningKh: "បឋម", example: "The preliminary results are good.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "presume", meaning: "to suppose to be true", meaningKh: "សន្មត", example: "I presume you are tired.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "prohibit", meaning: "to forbid by authority", meaningKh: "ហាមឃាត់", example: "Smoking is prohibited here.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "prominent", meaning: "important; standing out", meaningKh: "លេចធ្លោ", example: "He is a prominent scientist.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "proportion", meaning: "a part in relation to the whole", meaningKh: "សមាមាត្រ", example: "A large proportion of students passed.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "protocol", meaning: "official rules of conduct", meaningKh: "ពិធីការ", example: "Follow the safety protocol.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "psychological", meaning: "of the mind", meaningKh: "ផ្លូវចិត្ត", example: "She needs psychological help.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "qualitative", meaning: "relating to quality", meaningKh: "គុណភាព", example: "We did qualitative research.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "quantitative", meaning: "relating to quantity", meaningKh: "បរិមាណ", example: "Quantitative data shows the trend.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "radical", meaning: "thorough; extreme", meaningKh: "រ៉ាឌីកាល់", example: "He proposed radical changes.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "random", meaning: "made without a pattern", meaningKh: "ដោយចៃដន្យ", example: "Pick a random number.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "refine", meaning: "to improve by removing impurities", meaningKh: "ចម្រាញ់", example: "She refined her writing style.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "reinforce", meaning: "to strengthen", meaningKh: "ពង្រឹង", example: "Concrete reinforces the wall.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "render", meaning: "to provide; to cause to be", meaningKh: "ធ្វើឱ្យ", example: "The shock rendered her speechless.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "reside", meaning: "to live in a place", meaningKh: "រស់នៅ", example: "They reside in Phnom Penh.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "restrain", meaning: "to hold back", meaningKh: "រឹតបន្តឹង", example: "She could hardly restrain her anger.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "rigid", meaning: "stiff; not flexible", meaningKh: "តឹង", example: "He follows rigid rules.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "robust", meaning: "strong and healthy", meaningKh: "ខ្លាំងមាំ", example: "The economy is robust.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "scenario", meaning: "a possible situation", meaningKh: "សេណារីយ៉ូ", example: "Plan for the worst-case scenario.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "scheme", meaning: "a plan or arrangement", meaningKh: "គម្រោងការ", example: "She has a clever scheme.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "scope", meaning: "the range of an activity", meaningKh: "វិសាលភាព", example: "This is outside the scope of our work.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "sector", meaning: "a section of an economy or area", meaningKh: "វិស័យ", example: "She works in the tech sector.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "seek", meaning: "to try to find or obtain", meaningKh: "ស្វែងរក", example: "Seek and you shall find.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "selective", meaning: "carefully choosing", meaningKh: "ជ្រើសរើស", example: "She is selective about friends.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "sequence", meaning: "a particular order", meaningKh: "លំដាប់", example: "Follow the correct sequence.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "simulate", meaning: "to imitate; to pretend", meaningKh: "ធ្វើត្រាប់តាម", example: "The pilot simulated a landing.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "specialist", meaning: "an expert in a field", meaningKh: "អ្នកជំនាញ", example: "She's a heart specialist.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "specify", meaning: "to state exactly", meaningKh: "បញ្ជាក់ច្បាស់", example: "Please specify your needs.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "stability", meaning: "the state of being steady", meaningKh: "ស្ថិរភាព", example: "Political stability is important.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "straightforward", meaning: "simple and clear", meaningKh: "សាមញ្ញ", example: "The instructions are straightforward.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "subordinate", meaning: "lower in rank", meaningKh: "ក្រោមបង្គាប់", example: "A captain is subordinate to a general.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "subsequent", meaning: "coming after", meaningKh: "បន្ទាប់", example: "Subsequent events proved her right.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "subsidy", meaning: "money given by the government", meaningKh: "ឧបត្ថម្ភ", example: "Farmers receive subsidies.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "supplement", meaning: "to add to", meaningKh: "បំពេញបន្ថែម", example: "She takes vitamin supplements.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "sustainable", meaning: "able to continue without harm", meaningKh: "ចីរភាព", example: "Sustainable energy is the future.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "symbolic", meaning: "representing something else", meaningKh: "និមិត្តរូប", example: "The gesture was symbolic.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "tackle", meaning: "to confront or deal with", meaningKh: "ដោះស្រាយ", example: "Let's tackle this problem.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "technical", meaning: "relating to a particular subject or skill", meaningKh: "បច្ចេកទេស", example: "He has technical knowledge.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "terminate", meaning: "to end", meaningKh: "បញ្ចប់", example: "They terminated his contract.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "theoretical", meaning: "based on theory, not practice", meaningKh: "ទ្រឹស្តី", example: "This is a theoretical issue.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "thereby", meaning: "by that means", meaningKh: "ដោយហេតុនេះ", example: "She stayed late, thereby finishing on time.", partOfSpeech: "adverb", level: Level.ADVANCED },
  { word: "threshold", meaning: "the entrance; a starting point", meaningKh: "កម្រិតចាប់ផ្តើម", example: "She stood at the threshold.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "transmit", meaning: "to send out", meaningKh: "បញ្ជូន", example: "Radio waves transmit sound.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "trigger", meaning: "to cause something to start", meaningKh: "បង្ក", example: "The smell triggered a memory.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "ultimate", meaning: "final; most extreme", meaningKh: "ចុងបញ្ចប់", example: "Her ultimate goal is success.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "undergo", meaning: "to experience", meaningKh: "ឆ្លងកាត់", example: "She underwent surgery.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "undertake", meaning: "to commit oneself to a task", meaningKh: "ទទួលយក", example: "He undertook the difficult project.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "uniform", meaning: "the same throughout; identical clothing", meaningKh: "ឯកសណ្ឋាន", example: "Apply uniform pressure.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "unique", meaning: "one of a kind", meaningKh: "តែមួយគត់", example: "Every snowflake is unique.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "utilize", meaning: "to make use of", meaningKh: "ប្រើប្រាស់", example: "Utilize all available resources.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "valid", meaning: "acceptable; legally sound", meaningKh: "មានសុពលភាព", example: "Your point is valid.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "variable", meaning: "able to change; changeable", meaningKh: "អថេរ", example: "Weather is highly variable.", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "viable", meaning: "capable of working", meaningKh: "មានលទ្ធភាព", example: "Is this a viable solution?", partOfSpeech: "adjective", level: Level.ADVANCED },
  { word: "visualize", meaning: "to form a mental image", meaningKh: "ស្រមៃមើល", example: "Visualize your success.", partOfSpeech: "verb", level: Level.ADVANCED },
  { word: "workforce", meaning: "the people who work", meaningKh: "កម្លាំងពលកម្ម", example: "The company has a large workforce.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "yield", meaning: "to produce; to give way", meaningKh: "ផ្តល់ផល", example: "The land yields good rice.", partOfSpeech: "verb", level: Level.ADVANCED },
];
