import { Level } from "@prisma/client";
import type { VocabEntry } from "./types";

export const babyRoomVocab: VocabEntry[] = [
  { word: "teddy bear", meaning: "a soft stuffed bear toy", meaningKh: "ខ្លាឃ្មុំខ្ទភ", example: "The child hugged her teddy bear.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "intercom", meaning: "a system for speaking between rooms", meaningKh: "អន្តរកម្មវិធីទូរស័ព្ទ", example: "Use the intercom to listen to the baby.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "crib", meaning: "a small bed with high sides for a baby", meaningKh: "គ្រាប់ទារក", example: "The baby slept in the crib.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "crib bumper", meaning: "a padded liner around the inside of a crib", meaningKh: "ក្រដាសការពារគ្រាប់ទារក", example: "Attach the crib bumper inside the rails.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "mobile", meaning: "a hanging toy that moves above a crib", meaningKh: "គីអ៊ុយព្យួរគ្រាប់ទារក", example: "The mobile played soft music.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "crib toy", meaning: "a toy made for use in or on a crib", meaningKh: "ប្រដាប់លេងគ្រាប់ទារក", example: "Hang a crib toy where the baby can reach it.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "night light", meaning: "a dim light left on at night", meaningKh: "ភ្លើងយប់", example: "A night light helps the baby feel safe.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "changing table", meaning: "a table for changing a baby's diaper (also called a dressing table)", meaningKh: "តុប្តូរទារក", example: "Keep supplies on the changing table.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "stretch suit", meaning: "a one-piece outfit that stretches for a baby", meaningKh: "សម្លៀកបំពាក់ទារក", example: "She dressed the baby in a stretch suit.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "changing pad", meaning: "a padded surface for changing diapers", meaningKh: "ក្រាលប្តូរទារក", example: "Wipe the changing pad after each use.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "diaper pail", meaning: "a container for used diapers", meaningKh: "ធុងទារក", example: "Empty the diaper pail every day.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "toy chest", meaning: "a box or chest for storing toys", meaningKh: "ទ្រូងលេង", example: "Put the blocks back in the toy chest.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "doll", meaning: "a toy figure made to look like a person", meaningKh: "តុក្កវ៉ា", example: "She played with her doll.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "swing", meaning: "a seat that moves back and forth for a baby", meaningKh: "ពព័រកាត់", example: "The baby fell asleep in the swing.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "playpen", meaning: "a portable enclosed area where a baby can play safely", meaningKh: "ក្រឡាលេង", example: "Set up the playpen in the living room.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "stuffed animal", meaning: "a soft toy animal filled with stuffing", meaningKh: "សត្វដាក់ពញ", example: "He collects stuffed animals.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "rattle", meaning: "a baby toy that makes a shaking sound", meaningKh: "កណ្តឹងទារក", example: "The baby shook the rattle.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "cradle", meaning: "a small bed that rocks for a baby", meaningKh: "គ្រាប់ទារករៀប", example: "The cradle rocked gently.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "walker", meaning: "a frame on wheels that helps a baby learn to walk", meaningKh: "ម៉ាស៊ីនដើរទារក", example: "The baby pushed the walker across the floor.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "car seat", meaning: "a safety seat for a child in a car", meaningKh: "កៅអីរថយន្ត", example: "Buckle the baby into the car seat.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "stroller", meaning: "a wheeled chair for pushing a baby", meaningKh: "រទេះរុញទារក", example: "They folded the stroller into the trunk.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "baby carriage", meaning: "a wheeled bed for carrying a baby (also called a pram)", meaningKh: "រទេះទារក", example: "She pushed the baby carriage through the park.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "food warmer", meaning: "a device that warms baby bottles or food", meaningKh: "ម៉ាស៊ីនកំដៅអាហារ", example: "Heat the bottle in the food warmer.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "booster seat", meaning: "a raised seat so a child can sit at a table", meaningKh: "កៅអីឧត្តម", example: "The toddler sat in a booster seat.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "baby seat", meaning: "a small seat for holding a baby safely", meaningKh: "កៅអីទារក", example: "Place the baby seat on the floor.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "high chair", meaning: "a tall chair with a tray for feeding a baby", meaningKh: "កៅអីខ្ពស់", example: "Strap the baby into the high chair.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "portable crib", meaning: "a crib that folds for travel", meaningKh: "គ្រាប់ទារកចល័ត", example: "Pack the portable crib for the trip.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "baby carrier", meaning: "a pack or sling for carrying a baby on your body", meaningKh: "ថង់ដាក់ទារក", example: "She wore the baby in a baby carrier.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "potty", meaning: "a small toilet for toilet training a child", meaningKh: "បង្គន់ទារក", example: "The toddler is learning to use the potty.", partOfSpeech: "noun", level: Level.BEGINNER },
];
