import { Level } from "@prisma/client";
import type { VocabEntry } from "./types";

/** 100 essential beginner words — greetings, people, home, time, body, colors, verbs, adjectives. */
export const basicWordsVocab: VocabEntry[] = [
  { word: "hello", meaning: "a greeting when you meet someone", meaningKh: "សួស្តី", example: "Hello, how are you?", partOfSpeech: "interjection", level: Level.BEGINNER },
  { word: "goodbye", meaning: "what you say when you leave", meaningKh: "លាហើយ", example: "Goodbye, see you tomorrow.", partOfSpeech: "interjection", level: Level.BEGINNER },
  { word: "please", meaning: "a polite word when you ask for something", meaningKh: "សូម", example: "Please sit down.", partOfSpeech: "adverb", level: Level.BEGINNER },
  { word: "thank you", meaning: "what you say when someone helps you", meaningKh: "អរគុណ", example: "Thank you for your help.", partOfSpeech: "phrase", level: Level.BEGINNER },
  { word: "sorry", meaning: "what you say when you did something wrong", meaningKh: "សុំទោស", example: "Sorry, I am late.", partOfSpeech: "interjection", level: Level.BEGINNER },
  { word: "yes", meaning: "used to agree or answer positively", meaningKh: "បាទ/ចាស", example: "Yes, I understand.", partOfSpeech: "adverb", level: Level.BEGINNER },
  { word: "no", meaning: "used to refuse or answer negatively", meaningKh: "ទេ", example: "No, thank you.", partOfSpeech: "adverb", level: Level.BEGINNER },
  { word: "excuse me", meaning: "a polite phrase to get attention or apologize", meaningKh: "អត់ទាន់", example: "Excuse me, where is the bank?", partOfSpeech: "phrase", level: Level.BEGINNER },
  { word: "help", meaning: "to make it easier for someone to do something", meaningKh: "ជួយ", example: "Can you help me?", partOfSpeech: "verb", level: Level.BEGINNER },

  { word: "I", meaning: "the person speaking", meaningKh: "ខ្ញុំ", example: "I am a student.", partOfSpeech: "pronoun", level: Level.BEGINNER },
  { word: "you", meaning: "the person being spoken to", meaningKh: "អ្នក", example: "You are very kind.", partOfSpeech: "pronoun", level: Level.BEGINNER },
  { word: "he", meaning: "a male person already mentioned", meaningKh: "គាត់", example: "He is my brother.", partOfSpeech: "pronoun", level: Level.BEGINNER },
  { word: "she", meaning: "a female person already mentioned", meaningKh: "នាង", example: "She is my sister.", partOfSpeech: "pronoun", level: Level.BEGINNER },
  { word: "we", meaning: "I and other people together", meaningKh: "យើង", example: "We live in Phnom Penh.", partOfSpeech: "pronoun", level: Level.BEGINNER },
  { word: "they", meaning: "those people", meaningKh: "ពួកគេ", example: "They are my friends.", partOfSpeech: "pronoun", level: Level.BEGINNER },
  { word: "it", meaning: "a thing or animal already mentioned", meaningKh: "វា", example: "It is very hot today.", partOfSpeech: "pronoun", level: Level.BEGINNER },
  { word: "my", meaning: "belonging to me", meaningKh: "របស់ខ្ញុំ", example: "This is my book.", partOfSpeech: "determiner", level: Level.BEGINNER },
  { word: "your", meaning: "belonging to you", meaningKh: "របស់អ្នក", example: "What is your name?", partOfSpeech: "determiner", level: Level.BEGINNER },
  { word: "this", meaning: "the thing near you", meaningKh: "នេះ", example: "This is my phone.", partOfSpeech: "determiner", level: Level.BEGINNER },
  { word: "that", meaning: "the thing farther away", meaningKh: "នោះ", example: "That house is big.", partOfSpeech: "determiner", level: Level.BEGINNER },
  { word: "here", meaning: "in this place", meaningKh: "នៅទីនេះ", example: "Come here, please.", partOfSpeech: "adverb", level: Level.BEGINNER },
  { word: "there", meaning: "in that place", meaningKh: "នៅទីនោះ", example: "The shop is over there.", partOfSpeech: "adverb", level: Level.BEGINNER },
  { word: "who", meaning: "used to ask about a person", meaningKh: "អ្នកណា", example: "Who is that man?", partOfSpeech: "pronoun", level: Level.BEGINNER },
  { word: "what", meaning: "used to ask about a thing", meaningKh: "អ្វី", example: "What is your job?", partOfSpeech: "pronoun", level: Level.BEGINNER },
  { word: "where", meaning: "used to ask about a place", meaningKh: "នៅឯណា", example: "Where do you live?", partOfSpeech: "adverb", level: Level.BEGINNER },
  { word: "when", meaning: "used to ask about time", meaningKh: "ពេលណា", example: "When does the class start?", partOfSpeech: "adverb", level: Level.BEGINNER },
  { word: "why", meaning: "used to ask for a reason", meaningKh: "ហេតុអ្វី", example: "Why are you late?", partOfSpeech: "adverb", level: Level.BEGINNER },
  { word: "how", meaning: "used to ask about manner or way", meaningKh: "ដូចម្តេច", example: "How do you spell that?", partOfSpeech: "adverb", level: Level.BEGINNER },

  { word: "and", meaning: "used to join words or ideas", meaningKh: "និង", example: "Bread and butter.", partOfSpeech: "conjunction", level: Level.BEGINNER },
  { word: "or", meaning: "used to show a choice", meaningKh: "ឬ", example: "Tea or coffee?", partOfSpeech: "conjunction", level: Level.BEGINNER },
  { word: "but", meaning: "used to show contrast", meaningKh: "ប៉ុន្តែ", example: "Small but strong.", partOfSpeech: "conjunction", level: Level.BEGINNER },
  { word: "now", meaning: "at this moment", meaningKh: "ឥឡូវ", example: "I am busy now.", partOfSpeech: "adverb", level: Level.BEGINNER },
  { word: "today", meaning: "this day", meaningKh: "ថ្ងៃនេះ", example: "Today is Monday.", partOfSpeech: "adverb", level: Level.BEGINNER },
  { word: "tomorrow", meaning: "the day after today", meaningKh: "ថ្ងៃស្អែក", example: "See you tomorrow.", partOfSpeech: "adverb", level: Level.BEGINNER },

  { word: "man", meaning: "an adult male person", meaningKh: "បុរស", example: "The man is tall.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "woman", meaning: "an adult female person", meaningKh: "ស្ត្រី", example: "The woman is a doctor.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "boy", meaning: "a male child", meaningKh: "ក្មេងប្រុស", example: "The boy plays football.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "girl", meaning: "a female child", meaningKh: "ក្មេងស្រី", example: "The girl reads a book.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "child", meaning: "a young person", meaningKh: "កុមារ", example: "Every child needs love.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "baby", meaning: "a very young child", meaningKh: "ទារក", example: "The baby is sleeping.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "mother", meaning: "a female parent", meaningKh: "ម្តាយ", example: "My mother cooks well.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "father", meaning: "a male parent", meaningKh: "ឪពុក", example: "His father works hard.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "brother", meaning: "a male sibling", meaningKh: "បង/ប្អូនប្រុស", example: "I have one brother.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "sister", meaning: "a female sibling", meaningKh: "បង/ប្អូនស្រី", example: "She is my older sister.", partOfSpeech: "noun", level: Level.BEGINNER },

  { word: "family", meaning: "parents, children, and relatives together", meaningKh: "គ្រួសារ", example: "Family is important.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "friend", meaning: "a person you like and trust", meaningKh: "មិត្ត", example: "He is my best friend.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "people", meaning: "human beings in general", meaningKh: "មនុស្ស", example: "Many people live here.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "name", meaning: "what someone or something is called", meaningKh: "ឈ្មោះ", example: "What is your name?", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "home", meaning: "the place where you live", meaningKh: "ផ្ទះ", example: "I go home at five.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "house", meaning: "a building where people live", meaningKh: "ផ្ទះ", example: "They bought a new house.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "room", meaning: "a part of a building with walls", meaningKh: "បន្ទប់", example: "My room is small.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "door", meaning: "what you open to enter a room", meaningKh: "ទ្វារ", example: "Close the door, please.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "window", meaning: "an opening in a wall with glass", meaningKh: "បង្អួច", example: "Open the window.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "kitchen", meaning: "a room where food is cooked", meaningKh: "ផ្ទះបាយ", example: "She is in the kitchen.", partOfSpeech: "noun", level: Level.BEGINNER },

  { word: "day", meaning: "a period of 24 hours", meaningKh: "ថ្ងៃ", example: "Have a nice day.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "night", meaning: "the dark part of the day", meaningKh: "យប់", example: "Good night.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "morning", meaning: "the early part of the day", meaningKh: "ព្រឹក", example: "I run every morning.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "week", meaning: "a period of seven days", meaningKh: "សប្តាហ៍", example: "I work five days a week.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "time", meaning: "minutes, hours, days, etc.", meaningKh: "ពេលវេលា", example: "What time is it?", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "one", meaning: "the number 1", meaningKh: "មួយ", example: "I have one brother.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "two", meaning: "the number 2", meaningKh: "ពីរ", example: "Two cups of tea.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "three", meaning: "the number 3", meaningKh: "បី", example: "Three little birds.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "head", meaning: "the top part of your body with your face", meaningKh: "ក្បាល", example: "My head hurts.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "hand", meaning: "the part at the end of your arm", meaningKh: "ដៃ", example: "Wash your hands.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "foot", meaning: "the part at the end of your leg", meaningKh: "ជើង", example: "My foot is sore.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "eye", meaning: "the body part you see with", meaningKh: "ភ្នែក", example: "She has brown eyes.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "ear", meaning: "the body part you hear with", meaningKh: "ត្រចៀក", example: "He whispered in my ear.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "mouth", meaning: "the part of the face you eat and speak with", meaningKh: "មាត់", example: "Open your mouth.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "red", meaning: "the color of blood", meaningKh: "ក្រហម", example: "She wore a red dress.", partOfSpeech: "adjective", level: Level.BEGINNER },
  { word: "blue", meaning: "the color of the sky", meaningKh: "ខៀវ", example: "The sky is blue.", partOfSpeech: "adjective", level: Level.BEGINNER },
  { word: "green", meaning: "the color of grass", meaningKh: "បៃតង", example: "Green vegetables are healthy.", partOfSpeech: "adjective", level: Level.BEGINNER },
  { word: "sun", meaning: "the star that gives light and heat", meaningKh: "ព្រះអាទិត្យ", example: "The sun is bright.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "rain", meaning: "water that falls from clouds", meaningKh: "ភ្លៀង", example: "It will rain today.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "dog", meaning: "a common pet animal that barks", meaningKh: "ឆ្កែ", example: "The dog is friendly.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "cat", meaning: "a small pet animal that meows", meaningKh: "ឆ្មា", example: "The cat sleeps a lot.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "go", meaning: "to move from one place to another", meaningKh: "ទៅ", example: "I go to school.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "come", meaning: "to move toward the speaker", meaningKh: "មក", example: "Please come here.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "eat", meaning: "to put food in your mouth and swallow", meaningKh: "ញ៉ាំ", example: "Let's eat lunch.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "drink", meaning: "to swallow liquid", meaningKh: "ផឹក", example: "Drink more water.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "sleep", meaning: "to rest with your eyes closed", meaningKh: "ដេក", example: "I sleep eight hours.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "work", meaning: "to do a job or task", meaningKh: "ធ្វើការ", example: "She works in an office.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "read", meaning: "to look at words and understand them", meaningKh: "អាន", example: "I read every day.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "write", meaning: "to make letters or words on paper", meaningKh: "សរសេរ", example: "Write your name here.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "speak", meaning: "to say words; to talk", meaningKh: "និយាយ", example: "Do you speak English?", partOfSpeech: "verb", level: Level.BEGINNER },

  { word: "see", meaning: "to notice with your eyes", meaningKh: "ឃើញ", example: "I see a bird.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "hear", meaning: "to notice with your ears", meaningKh: "ឮ", example: "Can you hear me?", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "know", meaning: "to have information in your mind", meaningKh: "ដឹង", example: "I know the answer.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "think", meaning: "to use your mind", meaningKh: "គិត", example: "I think you are right.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "want", meaning: "to wish for something", meaningKh: "ចង់", example: "I want some water.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "like", meaning: "to enjoy something", meaningKh: "ចូលចិត្ត", example: "I like this song.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "love", meaning: "to care for someone or something deeply", meaningKh: "ស្រឡាញ់", example: "I love my family.", partOfSpeech: "verb", level: Level.BEGINNER },

  { word: "good", meaning: "of high quality or nice", meaningKh: "ល្អ", example: "That is a good idea.", partOfSpeech: "adjective", level: Level.BEGINNER },
  { word: "bad", meaning: "not good; harmful", meaningKh: "អាក្រក់", example: "Bad weather today.", partOfSpeech: "adjective", level: Level.BEGINNER },
  { word: "big", meaning: "large in size", meaningKh: "ធំ", example: "A big house.", partOfSpeech: "adjective", level: Level.BEGINNER },
  { word: "small", meaning: "little in size", meaningKh: "តូច", example: "A small bag.", partOfSpeech: "adjective", level: Level.BEGINNER },
  { word: "hot", meaning: "having a high temperature", meaningKh: "ក្តៅ", example: "The soup is hot.", partOfSpeech: "adjective", level: Level.BEGINNER },
  { word: "cold", meaning: "having a low temperature", meaningKh: "ត្រជាក់", example: "It is cold outside.", partOfSpeech: "adjective", level: Level.BEGINNER },
  { word: "happy", meaning: "feeling pleasure or joy", meaningKh: "សប្បាយ", example: "She looks happy.", partOfSpeech: "adjective", level: Level.BEGINNER },
  { word: "sad", meaning: "feeling unhappy", meaningKh: "ក្រៀមក្រំ", example: "Why are you sad?", partOfSpeech: "adjective", level: Level.BEGINNER },
  { word: "easy", meaning: "not difficult", meaningKh: "ងាយ", example: "This lesson is easy.", partOfSpeech: "adjective", level: Level.BEGINNER },
];
