import { Level } from "@prisma/client";
import type { VocabEntry } from "./types";

export const bathroomVocab: VocabEntry[] = [
  { word: "plunger", meaning: "a tool used to clear a blocked toilet or drain", meaningKh: "ឧបករណ៍រុញទឹក", example: "Use a plunger when the toilet won't flush.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "toilet", meaning: "a fixture for urinating and defecating", meaningKh: "បង្គន់", example: "Flush the toilet after use.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "toilet tank", meaning: "the upper part of a toilet that holds water for flushing", meaningKh: "ធុងបង្គន់", example: "Lift the lid on the toilet tank.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "toilet seat", meaning: "the hinged seat on a toilet", meaningKh: "កៅអីបង្គន់", example: "Lower the toilet seat gently.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "air freshener", meaning: "a spray or device that makes air smell pleasant", meaningKh: "ស្ព្រេយ៍បំបាត់ក្លិន", example: "Spray air freshener in the bathroom.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "toilet paper holder", meaning: "a fixture that holds a roll of toilet paper", meaningKh: "ការកដាក់ក្រដាសបង្គន់", example: "Mount the toilet paper holder on the wall.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "toilet paper", meaning: "soft paper used after using the toilet", meaningKh: "ក្រដាសបង្គន់", example: "We need to buy more toilet paper.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "toilet brush", meaning: "a brush for cleaning the inside of a toilet", meaningKh: "ច្រាសដុសបង្គន់", example: "Scrub with the toilet brush and cleaner.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "towel rack", meaning: "a bar or rack for hanging towels", meaningKh: "រន្ធដាក់កន្សែង", example: "Hang the towel on the towel rack.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "bath towel", meaning: "a large towel used after bathing", meaningKh: "កន្សែងងូតទឹក", example: "Dry off with a clean bath towel.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "hand towel", meaning: "a smaller towel for drying hands", meaningKh: "កន្សែងជម្រះដៃ", example: "Replace the hand towel every few days.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "washcloth", meaning: "a small cloth for washing the face or body (also called a facecloth)", meaningKh: "ក្រណាត់លាង", example: "Wet the washcloth with warm water.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "hamper", meaning: "a basket for dirty laundry", meaningKh: "ថង់ខោអាវករណី", example: "Throw your clothes in the hamper.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "bathroom scale", meaning: "a scale used to measure body weight", meaningKh: "តុក្រាស់ទម្ងន់", example: "Step on the bathroom scale.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "shelf", meaning: "a flat board fixed to a wall for holding items", meaningKh: "ធ្នើ", example: "Put extra soap on the shelf.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "hair dryer", meaning: "an electric device that blows hot air to dry hair", meaningKh: "ម៉ាស៊ីនបម្រៀងសក់", example: "Plug in the hair dryer after your shower.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "fan", meaning: "a device that moves air to cool a room", meaningKh: "កង្ហារ", example: "Turn on the fan to reduce humidity.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "medicine cabinet", meaning: "a mirrored cabinet for storing medicines (also called a medicine chest)", meaningKh: "ទូថ្នាំ", example: "Keep aspirin in the medicine cabinet.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "bathroom sink", meaning: "a basin with a faucet for washing in the bathroom", meaningKh: "លិចបន្ទប់ទឹក", example: "Brush your teeth at the bathroom sink.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "hot water faucet", meaning: "the tap that releases hot water", meaningKh: "កុងទឹកក្តៅ", example: "Turn the hot water faucet slowly.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "cold water faucet", meaning: "the tap that releases cold water", meaningKh: "កុងទឹកត្រជាក់", example: "Start with the cold water faucet.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "cup", meaning: "a small container for rinsing or holding water in the bathroom", meaningKh: "ពែង", example: "Fill the cup with water to rinse.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "toothbrush", meaning: "a brush for cleaning teeth", meaningKh: "ច្រាសដុសធ្មេញ", example: "Replace your toothbrush every three months.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "toothbrush holder", meaning: "a cup or stand that holds toothbrushes", meaningKh: "ការកដាក់ច្រាសដុសធ្មេញ", example: "Rinse the toothbrush holder weekly.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "soap", meaning: "a substance used with water for washing", meaningKh: "សាប៊ូ", example: "Wash your hands with soap.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "soap dish", meaning: "a small dish that holds a bar of soap", meaningKh: "ចានដាក់សាប៊ូ", example: "The soap dish sits by the sink.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "soap dispenser", meaning: "a container that pumps out liquid soap", meaningKh: "ឧបករណ៍បញ្ចេញសាប៊ូ", example: "Refill the soap dispenser.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "water pick", meaning: "a device that sprays water between teeth (brand: Water Pik)", meaningKh: "ម៉ាស៊ីនខ្ពស់ទឹកជម្រះធ្មេញ", example: "Use a water pick after flossing.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "vanity", meaning: "a bathroom cabinet with a sink and mirror", meaningKh: "ទូលិចបន្ទប់ទឹក", example: "Store makeup in the vanity drawers.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "wastebasket", meaning: "a small bin for trash in a room", meaningKh: "ធុងសំណល់តូច", example: "Empty the wastebasket often.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "shower", meaning: "a fixture or stall for washing under spraying water", meaningKh: "ផ្កាទឹករាង", example: "Take a quick shower before work.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "shower curtain rod", meaning: "the rod that holds a shower curtain", meaningKh: "របងពូកផ្កាទឹក", example: "Install the shower curtain rod securely.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "shower head", meaning: "the part of a shower that sprays water", meaningKh: "ក្បាលផ្កាទឹក", example: "Clean mineral buildup from the shower head.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "shower curtain rings", meaning: "rings that attach a curtain to the rod", meaningKh: "កងពូកផ្កាទឹក", example: "Snap the shower curtain rings onto the rod.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "shower curtain", meaning: "a waterproof curtain around a shower", meaningKh: "ពូកផ្កាទឹក", example: "Close the shower curtain while you wash.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "bathtub", meaning: "a large tub for bathing (also called a tub)", meaningKh: "អាងងូតទឹក", example: "Fill the bathtub with warm water.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "drain", meaning: "an opening that carries away water", meaningKh: "រន្ធលុះទឹក", example: "Hair can clog the drain.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "rubber mat", meaning: "a rubber mat that prevents slipping in the tub or shower", meaningKh: "កំរាលកៅស៊ូ", example: "Place a rubber mat in the bathtub.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "bath mat", meaning: "a mat on the floor outside the tub to absorb water (also called a bath rug)", meaningKh: "កំរាលទម្រាប់អាង", example: "Step onto the bath mat after your shower.", partOfSpeech: "noun", level: Level.BEGINNER },
];
