import { Level } from "@prisma/client";
import type { VocabEntry } from "./types";

export const classroomActionsVocab: VocabEntry[] = [
  { word: "stand up", meaning: "to rise from a sitting position to a standing one", meaningKh: "ក្រោកឈរ", example: "Please stand up when the teacher enters.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "go to the board", meaning: "to walk up to the classroom board to write", meaningKh: "ទៅកាន់ក្តារខៀន", example: "Go to the board and solve the problem.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "write your name", meaning: "to put your name on paper or a board", meaningKh: "សរសេរឈ្មោះ", example: "Write your name at the top of the page.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "erase your name", meaning: "to remove your name from a board or paper", meaningKh: "លុបឈ្មោះ", example: "Erase your name and try again.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "sit down", meaning: "to take a seat (also: take your seat)", meaningKh: "អង្គុយ", example: "Please sit down quietly.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "open your book", meaning: "to lift the cover of a book to begin reading", meaningKh: "បើកសៀវភៅ", example: "Open your book to chapter three.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "read page eight", meaning: "to read the words on page eight of a book", meaningKh: "អានទំព័រទីប្រាំបី", example: "Read page eight silently.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "study page eight", meaning: "to learn the material on page eight carefully", meaningKh: "សិក្សាទំព័រទីប្រាំបី", example: "Study page eight for the quiz tomorrow.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "close your book", meaning: "to shut a book after reading", meaningKh: "បិទសៀវភៅ", example: "Close your book and listen carefully.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "put away your book", meaning: "to put a book back in its place when you finish", meaningKh: "ទុកសៀវភៅឲ្យត្រឹមត្រូវ", example: "Put away your book before lunch.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "listen to the question", meaning: "to hear and pay attention to a question", meaningKh: "ស្តាប់សំណួរ", example: "Listen to the question before you answer.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "raise your hand", meaning: "to lift your hand to ask or answer in class", meaningKh: "លើកដៃ", example: "Raise your hand if you know the answer.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "give the answer", meaning: "to say or write the answer to a question", meaningKh: "ឆ្លើយសំណួរ", example: "Give the answer in a complete sentence.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "work in groups", meaning: "to do an activity together with other students", meaningKh: "ធ្វើការជាក្រុម", example: "Work in groups of four to solve the puzzle.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "help each other", meaning: "to give help to one another", meaningKh: "ជួយគ្នាទៅវិញទៅមក", example: "Help each other with the new vocabulary.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "do your homework", meaning: "to complete schoolwork given to be done at home", meaningKh: "ធ្វើកិច្ចការផ្ទះ", example: "Do your homework before watching TV.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "bring in your homework", meaning: "to take your finished homework to school", meaningKh: "យកកិច្ចការផ្ទះមកសាលា", example: "Bring in your homework on Monday.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "go over the answers", meaning: "to review the answers together", meaningKh: "ពិនិត្យចម្លើយឡើងវិញ", example: "Let's go over the answers as a class.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "correct your mistakes", meaning: "to fix any errors you made", meaningKh: "កែកំហុស", example: "Correct your mistakes in red pen.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "hand in your homework", meaning: "to give your homework to the teacher", meaningKh: "ប្រគល់កិច្ចការផ្ទះ", example: "Hand in your homework before you leave.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "take out a piece of paper", meaning: "to get a sheet of paper ready to use", meaningKh: "យកក្រដាសមួយសន្លឹក", example: "Take out a piece of paper for the quiz.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "pass out the tests", meaning: "to give each student a test paper", meaningKh: "ចែកវិញ្ញាសា", example: "Pass out the tests row by row.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "answer the questions", meaning: "to give replies to questions", meaningKh: "ឆ្លើយសំណួរទាំងអស់", example: "Answer the questions in full sentences.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "check your answers", meaning: "to look over your answers to find mistakes", meaningKh: "ពិនិត្យចម្លើយ", example: "Check your answers before turning in the test.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "collect the tests", meaning: "to gather the finished tests from students", meaningKh: "ប្រមូលវិញ្ញាសា", example: "Collect the tests when time is up.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "lower the shades", meaning: "to pull window shades or blinds down", meaningKh: "បន្ទាបវាំងនន", example: "Lower the shades before the movie starts.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "turn off the lights", meaning: "to switch off the lights in a room", meaningKh: "បិទភ្លើង", example: "Turn off the lights when you leave.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "turn on the projector", meaning: "to switch on a projector to show images", meaningKh: "បើកម៉ាស៊ីនបញ្ចាំង", example: "Turn on the projector for the presentation.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "watch the movie", meaning: "to view a film", meaningKh: "មើលភាពយន្ត", example: "Watch the movie and take notes.", partOfSpeech: "verb", level: Level.BEGINNER },
  { word: "take notes", meaning: "to write down important information", meaningKh: "កត់ចំណាំ", example: "Take notes during the lecture.", partOfSpeech: "verb", level: Level.BEGINNER },
];
