import { Level } from "@prisma/client";
import type { VocabEntry } from "./types";

export const cleaningVocab: VocabEntry[] = [
  { word: "broom", meaning: "a brush with a long handle for sweeping floors", meaningKh: "អម្បោស", example: "Sweep the porch with a broom.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "dustpan", meaning: "a flat pan for collecting swept dust", meaningKh: "ចានជញ្ជីង", example: "Hold the dustpan while I sweep.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "whisk broom", meaning: "a small broom for quick cleanups", meaningKh: "អម្បោសតូច", example: "Use a whisk broom on the counter.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "feather duster", meaning: "a duster with feathers for dusting surfaces", meaningKh: "អម្បោសទរក", example: "Dust the shelves with a feather duster.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "dust cloth", meaning: "a cloth used for wiping dust", meaningKh: "ក្រណាត់ជូតធូលី", example: "Wipe the table with a dust cloth.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "iron", meaning: "a heated appliance for pressing clothes smooth", meaningKh: "ផ្ទាំងអ៊ីរ៉ូន", example: "Iron the shirt on low heat.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "ironing board", meaning: "a padded board used when ironing clothes", meaningKh: "ក្តារអ៊ីរ៉ូន", example: "Set up the ironing board in the laundry room.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "carpet sweeper", meaning: "a manual device for cleaning carpets", meaningKh: "ម៉ាស៊ីនសម្អាតកម្រាល", example: "Run the carpet sweeper over the rug.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "vacuum cleaner", meaning: "a machine that sucks up dirt from floors (also called a vacuum)", meaningKh: "ម៉ាស៊ីនទូទាត់ធូលី", example: "Vacuum the living room carpet.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "vacuum cleaner attachments", meaning: "extra tools that fit on a vacuum for corners and upholstery", meaningKh: "ឧបករណ៍បន្ថែមម៉ាស៊ីនទូទាត់", example: "Use vacuum cleaner attachments on the stairs.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "vacuum cleaner bag", meaning: "a disposable bag that collects dirt inside a vacuum", meaningKh: "ថង់ម៉ាស៊ីនទូទាត់", example: "Change the vacuum cleaner bag when full.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "hand vacuum", meaning: "a small portable vacuum for quick jobs", meaningKh: "ម៉ាស៊ីនទូទាត់ដៃ", example: "Clean crumbs with a hand vacuum.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "dust mop", meaning: "a dry mop for picking up dust (also called a dry mop)", meaningKh: "អម្បោសទូទាត់ធូលី", example: "Run the dust mop across the floor.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "sponge mop", meaning: "a mop with a sponge head for washing floors", meaningKh: "អម្បោសអេប៉ុង", example: "Rinse the sponge mop in the bucket.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "wet mop", meaning: "a mop used with water and cleaner on floors", meaningKh: "អម្បោសទឹក", example: "Mop the kitchen with a wet mop.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "washing machine", meaning: "a machine that washes clothes (also called a washer)", meaningKh: "ម៉ាស៊ីនបោកខោអាវ", example: "Load the washing machine and start the cycle.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "dryer", meaning: "a machine that dries clothes with heat", meaningKh: "ម៉ាស៊ីនសម្ងាត់", example: "Move clothes from the washer to the dryer.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "laundry detergent", meaning: "soap used for washing clothes", meaningKh: "សាប៊ូបោកខោអាវ", example: "Add laundry detergent to the washer.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "fabric softener", meaning: "a liquid that makes clothes feel softer", meaningKh: "ទឹករលោងក្រណាត់", example: "Pour fabric softener into the dispenser.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "bleach", meaning: "a strong chemical that whitens and disinfects", meaningKh: "ទឹកអុកស៊ីហ្សូ", example: "Use bleach only on white fabrics.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "starch", meaning: "a substance that stiffens fabric when ironing", meaningKh: "ម្សៅរឹងក្រណាត់", example: "Spray starch before ironing pants.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "static cling remover", meaning: "a product that reduces static in clothes", meaningKh: "ទឹកបំបាត់ភ្លើងរញ្ជួយ", example: "Use static cling remover in the dryer.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "cleanser", meaning: "a cleaning product for surfaces", meaningKh: "ទឹកសម្អាត", example: "Spray cleanser on the counter.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "window cleaner", meaning: "a liquid for cleaning glass", meaningKh: "ទឹកសម្អាតកញ្កែវ", example: "Wipe the windows with window cleaner.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "ammonia", meaning: "a strong cleaning chemical with a sharp smell", meaningKh: "អាម៉ូញ៉ា", example: "Open windows when using ammonia.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "furniture polish", meaning: "a product that cleans and shines wood furniture", meaningKh: "ទឹកលាបគ្រឿងសង្ហារឹម", example: "Polish the table with furniture polish.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "floor wax", meaning: "a coating that protects and shines floors", meaningKh: "ទម្លាប់កម្រាល", example: "Apply floor wax in thin layers.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "paper towels", meaning: "absorbent disposable sheets for cleaning spills", meaningKh: "កោសក្រដាស", example: "Blot the spill with paper towels.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "hanger", meaning: "a shaped piece used to hang clothes in a closet", meaningKh: "ទំពក់ខ្ទាស់ខោអាវ", example: "Hang the coat on a hanger.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "laundry basket", meaning: "a basket for carrying dirty or clean laundry", meaningKh: "ថង់ខោអាវ", example: "Sort clothes into the laundry basket.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "laundry bag", meaning: "a bag for holding laundry", meaningKh: "ថង់បោកខោអាវ", example: "Pack a laundry bag for the trip.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "utility sink", meaning: "a deep sink for washing in a laundry or utility room", meaningKh: "លិចបោកខោអាវ", example: "Rinse muddy boots in the utility sink.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "scrub brush", meaning: "a stiff brush for scrubbing surfaces", meaningKh: "ច្រាសដុស", example: "Scrub the tile with a scrub brush.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "bucket", meaning: "a container with a handle for carrying liquids (also called a pail)", meaningKh: "ធុង", example: "Fill the bucket with soapy water.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "trash can", meaning: "a container for garbage (also called a garbage can)", meaningKh: "ធុងសំណល់", example: "Take the trash can to the curb.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "recycling bin", meaning: "a container for recyclable materials", meaningKh: "ធុងកែច្នៃ", example: "Put bottles in the recycling bin.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "clothesline", meaning: "a rope for hanging wet laundry to dry", meaningKh: "ខ្សែពួងខោអាវ", example: "Hang shirts on the clothesline.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "clothespins", meaning: "clips that hold laundry on a line", meaningKh: "ខ្ទមពួងខោអាវ", example: "Secure towels with clothespins.", partOfSpeech: "noun", level: Level.BEGINNER },
];
