import { Level } from "@prisma/client";
import type { VocabEntry } from "./types";

export const exteriorVocab: VocabEntry[] = [
  { word: "lamppost", meaning: "a tall post with a light on top outdoors", meaningKh: "បង្គោលភ្លើង", example: "The street has a lamppost on each corner.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "mailbox", meaning: "a box where mail is delivered or picked up", meaningKh: "ប្រអប់សំបុត្រ", example: "Check the mailbox for letters.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "front walk", meaning: "the path leading to the front door", meaningKh: "ផ្លូវទៅមុខផ្ទះ", example: "Shovel snow off the front walk.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "front steps", meaning: "the steps leading up to the front door", meaningKh: "ជណ្ដើរមុខផ្ទះ", example: "Sit on the front steps.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "front porch", meaning: "a covered area at the entrance of a house", meaningKh: "ពិដានមុខផ្ទះ", example: "We relaxed on the front porch.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "storm door", meaning: "an extra door outside the main door for weather protection", meaningKh: "ទ្វារការពារខ្យល់", example: "Close the storm door in winter.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "front door", meaning: "the main entrance door of a house", meaningKh: "ទ្វារមុខផ្ទះ", example: "Knock on the front door.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "doorbell", meaning: "a button that rings a bell when visitors arrive", meaningKh: "កណ្តឹងទ្វារ", example: "Press the doorbell.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "front light", meaning: "an outdoor light near the front entrance", meaningKh: "ភ្លើងមុខផ្ទះ", example: "Turn on the front light at dusk.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "window", meaning: "an opening in a wall with glass to let in light", meaningKh: "បង្អួច", example: "Open the window for fresh air.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "window screen", meaning: "a mesh cover that keeps insects out of a window", meaningKh: "សំណាញ់បង្អួច", example: "Repair the torn window screen.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "shutter", meaning: "hinged covers on the outside of a window", meaningKh: "បន្ទះបិទបង្អួច", example: "Close the shutters during the storm.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "roof", meaning: "the top covering of a building", meaningKh: "ដំបូល", example: "Leaves collected on the roof.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "TV antenna", meaning: "a device on a roof for receiving TV signals", meaningKh: "អង់តែណាទូរទស្សន៍", example: "The old house still has a TV antenna.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "chimney", meaning: "a structure that carries smoke up from a fireplace", meaningKh: "បំពាក់ផ្សែង", example: "Smoke rose from the chimney.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "garage", meaning: "a building or space for parking cars", meaningKh: "យានដ្ឋាន", example: "Park the car in the garage.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "garage door", meaning: "the large door at the entrance of a garage", meaningKh: "ទ្វារយានដ្ឋាន", example: "The garage door opens automatically.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "driveway", meaning: "a private road leading from the street to a house", meaningKh: "ផ្លូវចូលផ្ទះ", example: "Clear ice from the driveway.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "gutter", meaning: "a channel along the roof edge that carries rainwater", meaningKh: "របងទឹកភ្លៀង", example: "Clean leaves out of the gutter.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "downspout", meaning: "a pipe that carries water from a gutter to the ground (also called a drainpipe)", meaningKh: "បំពាក់ទឹក", example: "Water flowed through the downspout.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "deck", meaning: "a wooden platform attached to the back of a house", meaningKh: "ជាន់ឈើក្រៅ", example: "Grill dinner on the deck.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "back door", meaning: "the door at the rear of a house", meaningKh: "ទ្វារក្រោយផ្ទះ", example: "Let the dog in through the back door.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "doorknob", meaning: "a round handle for opening a door", meaningKh: "មុខទ្វារ", example: "Turn the doorknob slowly.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "screen door", meaning: "a door with mesh to keep insects out while allowing air in", meaningKh: "ទ្វារសំណាញ់", example: "Close the screen door behind you.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "side door", meaning: "a door on the side of a building", meaningKh: "ទ្វារចំហៀង", example: "Deliveries use the side door.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "satellite dish", meaning: "a dish-shaped antenna for satellite TV or internet", meaningKh: "ចានផ្កាយរណប", example: "Mount the satellite dish on the roof.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "patio", meaning: "a paved outdoor area next to a house", meaningKh: "ទីលានក្រៅ", example: "Set up chairs on the patio.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "lawnmower", meaning: "a machine for cutting grass", meaningKh: "ម៉ាស៊ីនកាត់ស្មៅ", example: "Push the lawnmower across the yard.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "barbecue grill", meaning: "an outdoor grill for cooking food (also called a barbecue)", meaningKh: "ចង្ក្រានអាំងសាច់", example: "Fire up the barbecue grill on Saturday.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "lawn chair", meaning: "a lightweight chair used outdoors on a lawn or patio", meaningKh: "កៅអីស្មៅ", example: "Fold the lawn chairs after the party.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "tool shed", meaning: "a small outdoor building for storing tools", meaningKh: "ផ្ទះល្វែងឧបករណ៍", example: "Keep the ladder in the tool shed.", partOfSpeech: "noun", level: Level.BEGINNER },
];
