import { Level } from "@prisma/client";
import type { VocabEntry } from "./types";

/** Additional B1 (intermediate) words from the B1 vocabulary list — only entries not already in other seeds. */
export const intermediateB1ExtraVocab: VocabEntry[] = [
  { word: "addition", meaning: "the act of adding something", meaningKh: "ការបន្ថែម", example: "In addition to math, she teaches science.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "agreement", meaning: "a formal arrangement", meaningKh: "កិច្ចព្រមព្រៀង", example: "They signed a peace agreement.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "album", meaning: "a collection of songs or photos", meaningKh: "សៀវភៅរូបថត", example: "She released a new album.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "alcohol", meaning: "a drink that can make you drunk", meaningKh: "គ្រឿងស្រវឹង", example: "Don't drink alcohol and drive.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "alternative", meaning: "another available option", meaningKh: "ជម្រើស", example: "Tea is a good alternative to coffee.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "ambition", meaning: "a strong desire to succeed", meaningKh: "មហិច្ឆតា", example: "Her ambition is to be a doctor.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "analysis", meaning: "careful examination", meaningKh: "ការវិភាគ", example: "The analysis took two weeks.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "apologize", meaning: "to say sorry", meaningKh: "សុំទោស", example: "He apologized for being late.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "appearance", meaning: "the way someone looks", meaningKh: "រូបរាងខាងក្រៅ", example: "Don't judge by appearance.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "application", meaning: "a formal request", meaningKh: "ការដាក់ពាក្យ", example: "She sent her application by email.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "arrival", meaning: "the act of arriving", meaningKh: "ការមកដល់", example: "We waited for her arrival.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "artificial", meaning: "made by humans, not natural", meaningKh: "សិប្បនិម្មិត", example: "The flowers are artificial.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "assignment", meaning: "a task given to someone", meaningKh: "កិច្ចការ", example: "I have a writing assignment.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "award", meaning: "a prize given for achievement", meaningKh: "រង្វាន់", example: "She won the best actress award.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "brand", meaning: "a type of product made by a company", meaningKh: "ម៉ាក", example: "What brand of phone do you use?", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "broadcast", meaning: "to send out by radio or TV", meaningKh: "ផ្សាយ", example: "The news is broadcast at six.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "burden", meaning: "a heavy load; a difficulty", meaningKh: "បន្ទុក", example: "Don't be a burden to your parents.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "classic", meaning: "of high quality and lasting value", meaningKh: "បុរាណល្បីល្បាញ", example: "It's a classic film.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "collapse", meaning: "to fall down suddenly", meaningKh: "រលំ", example: "The bridge collapsed in the storm.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "comfort", meaning: "a pleasant feeling of ease", meaningKh: "ភាពស្រួល", example: "She lives in comfort.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "commercial", meaning: "relating to business; an advertisement", meaningKh: "ពាណិជ្ជកម្ម", example: "He works in commercial radio.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "communication", meaning: "the sharing of information", meaningKh: "ការទំនាក់ទំនង", example: "Good communication is important.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "competition", meaning: "a contest between people or groups", meaningKh: "ការប្រកួត", example: "There's strong competition for the job.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "conference", meaning: "a formal meeting for discussion", meaningKh: "សន្និសីទ", example: "We attended an international conference.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "conscious", meaning: "awake and aware", meaningKh: "ដឹងខ្លួន", example: "She was conscious of his stare.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "contest", meaning: "a competition", meaningKh: "ការប្រកួត", example: "She won the singing contest.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "criminal", meaning: "a person who commits crimes", meaningKh: "ឧក្រិដ្ឋជន", example: "The criminal was caught quickly.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "critical", meaning: "extremely important; finding fault", meaningKh: "សំខាន់បំផុត", example: "She is in critical condition.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "dangerous", meaning: "likely to cause harm", meaningKh: "មានគ្រោះថ្នាក់", example: "Smoking is dangerous to health.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "delivery", meaning: "the act of bringing goods", meaningKh: "ការដឹកជញ្ជូន", example: "The delivery arrived this morning.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "desire", meaning: "a strong wish for something", meaningKh: "ប្រាថ្នាចង់បាន", example: "She has a desire to travel.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "despite", meaning: "in spite of", meaningKh: "ទោះបីជា", example: "We went out despite the rain.", partOfSpeech: "preposition", level: Level.INTERMEDIATE },
  { word: "dialogue", meaning: "a conversation between people", meaningKh: "ការសន្ទនា", example: "The film has clever dialogue.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "digital", meaning: "using numbers and computers", meaningKh: "ឌីជីថល", example: "We live in the digital age.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "dismiss", meaning: "to send away; to refuse to consider", meaningKh: "បញ្ឈប់", example: "The teacher dismissed the class.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "district", meaning: "an area of a town or country", meaningKh: "ស្រុក", example: "He lives in a quiet district.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "dominate", meaning: "to have power or control over", meaningKh: "គ្រប់គ្រងលើស", example: "The team dominated the game.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "dramatic", meaning: "sudden and noticeable", meaningKh: "គួរឱ្យភ្ញាក់ផ្អើល", example: "There was a dramatic change in weather.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "duty", meaning: "a moral or legal responsibility", meaningKh: "កាតព្វកិច្ច", example: "It's my duty to help.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "economic", meaning: "relating to the economy", meaningKh: "សេដ្ឋកិច្ច", example: "The country has economic problems.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "edition", meaning: "a particular version of a publication", meaningKh: "ការបោះពុម្ពលើកទី", example: "I have the first edition of the book.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "educate", meaning: "to teach or train", meaningKh: "អប់រំ", example: "Schools educate children.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "effective", meaning: "producing the desired result", meaningKh: "មានប្រសិទ្ធភាព", example: "The new medicine is very effective.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "election", meaning: "the process of voting", meaningKh: "ការបោះឆ្នោត", example: "The election will be next month.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "emphasis", meaning: "special importance given to something", meaningKh: "ការបញ្ជាក់", example: "She put emphasis on hard work.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "entertain", meaning: "to amuse or interest", meaningKh: "កម្សាន្ត", example: "He entertained the children with stories.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "equipment", meaning: "the tools needed for an activity", meaningKh: "សម្ភារ", example: "Bring your camping equipment.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "ethical", meaning: "morally right", meaningKh: "សីលធម៌", example: "It's not ethical to lie.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "eventually", meaning: "in the end", meaningKh: "នៅទីបំផុត", example: "She'll arrive eventually.", partOfSpeech: "adverb", level: Level.INTERMEDIATE },
  { word: "evolution", meaning: "gradual development", meaningKh: "វិវត្តន៍", example: "Darwin studied the evolution of species.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "expectation", meaning: "a belief about what will happen", meaningKh: "ការរំពឹងទុក", example: "She has high expectations.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "extent", meaning: "the degree of something", meaningKh: "ទំហំវិសាល", example: "To what extent is this true?", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "extraordinary", meaning: "very unusual or remarkable", meaningKh: "មិនធម្មតា", example: "She has extraordinary talent.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "failure", meaning: "a lack of success", meaningKh: "ការបរាជ័យ", example: "Failure can teach us lessons.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "fantastic", meaning: "extremely good", meaningKh: "ល្អណាស់", example: "We had a fantastic vacation.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "federal", meaning: "of a central government", meaningKh: "សហព័ន្ធ", example: "Federal law applies everywhere.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "feedback", meaning: "comments about work or performance", meaningKh: "មតិកែលម្អ", example: "Please give me feedback on my essay.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "fortune", meaning: "luck; a large amount of money", meaningKh: "សំណាង", example: "He made a fortune in business.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "freedom", meaning: "the right to act freely", meaningKh: "សេរីភាព", example: "Freedom of speech is important.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "furthermore", meaning: "in addition; moreover", meaningKh: "លើសពីនេះទៀត", example: "It's cheap; furthermore, it's reliable.", partOfSpeech: "adverb", level: Level.INTERMEDIATE },
  { word: "gallery", meaning: "a room or building for showing art", meaningKh: "វិចិត្រសាល", example: "We visited an art gallery.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "generation", meaning: "all people of about the same age", meaningKh: "ជំនាន់", example: "My grandparents' generation worked hard.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "gradually", meaning: "in a slow way over time", meaningKh: "បន្តិចម្តងៗ", example: "Her health improved gradually.", partOfSpeech: "adverb", level: Level.INTERMEDIATE },
  { word: "harmful", meaning: "causing harm", meaningKh: "បង្កគ្រោះថ្នាក់", example: "Too much sun is harmful.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "headline", meaning: "the main title of a news story", meaningKh: "ចំណងជើងព័ត៌មាន", example: "The story made the headlines.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "heavily", meaning: "to a great degree", meaningKh: "យ៉ាងធ្ងន់", example: "It rained heavily all night.", partOfSpeech: "adverb", level: Level.INTERMEDIATE },
  { word: "historical", meaning: "relating to the past", meaningKh: "ប្រវត្តិសាស្ត្រ", example: "Angkor Wat is a historical site.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "horror", meaning: "intense fear or shock", meaningKh: "ការភ័យរន្ធត់", example: "She watched in horror.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "humanity", meaning: "all human beings; kindness", meaningKh: "មនុស្សជាតិ", example: "We must protect humanity.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "humorous", meaning: "funny", meaningKh: "កំប្លែង", example: "He told a humorous story.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "imagination", meaning: "the ability to form mental images", meaningKh: "ការស្រមៃ", example: "Children have great imagination.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "immigrant", meaning: "a person who moves to a new country", meaningKh: "ជនអន្តោប្រវេសន៍", example: "Many immigrants live in this city.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "impression", meaning: "an effect on someone's mind", meaningKh: "ការចាប់អារម្មណ៍", example: "She made a good first impression.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "injure", meaning: "to harm physically", meaningKh: "ធ្វើឱ្យរបួស", example: "He injured his leg playing soccer.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "inner", meaning: "inside; located within", meaningKh: "ខាងក្នុង", example: "She has inner strength.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "inquiry", meaning: "an act of asking or investigating", meaningKh: "ការសាកសួរ", example: "We made an inquiry about prices.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "insist", meaning: "to demand firmly", meaningKh: "អះអាង", example: "She insisted on paying.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "inspect", meaning: "to examine carefully", meaningKh: "ត្រួតពិនិត្យ", example: "The official inspected the building.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "institution", meaning: "an established organization", meaningKh: "ស្ថាប័ន", example: "Universities are educational institutions.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "instruction", meaning: "a direction; teaching", meaningKh: "ការណែនាំ", example: "Follow the instructions carefully.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "insurance", meaning: "protection against loss", meaningKh: "ការធានារ៉ាប់រង", example: "Do you have car insurance?", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "interaction", meaning: "communication between people", meaningKh: "ការប្រាស្រ័យទាក់ទង", example: "Social interaction is important for kids.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "knowledge", meaning: "information and understanding", meaningKh: "ចំណេះដឹង", example: "Knowledge is power.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "leadership", meaning: "the ability to lead", meaningKh: "ភាពជាអ្នកដឹកនាំ", example: "Good leadership is essential.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "legend", meaning: "an old well-known story", meaningKh: "រឿងព្រេង", example: "He's a legend in Khmer music.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "liberal", meaning: "open to new ideas; generous", meaningKh: "សេរីនិយម", example: "She has liberal political views.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "lifetime", meaning: "the duration of a person's life", meaningKh: "មួយជីវិត", example: "It's a once-in-a-lifetime opportunity.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "limited", meaning: "restricted in size or number", meaningKh: "មានកំណត់", example: "Tickets are limited.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "location", meaning: "a particular place or position", meaningKh: "ទីតាំង", example: "The hotel has a great location.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "logical", meaning: "based on clear reasoning", meaningKh: "ត្រឹមត្រូវតាមតក្ក", example: "That's a logical answer.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "lonely", meaning: "feeling sad because alone", meaningKh: "ឯកោ", example: "She felt lonely after moving.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "marriage", meaning: "the state of being married", meaningKh: "ការរៀបអាពាហ៍ពិពាហ៍", example: "Their marriage is happy.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "massive", meaning: "very large", meaningKh: "ដ៏ធំ", example: "A massive crowd gathered.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "material", meaning: "the matter that something is made of", meaningKh: "សម្ភារ", example: "The shirt is made of soft material.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "mechanism", meaning: "the way something works", meaningKh: "យន្តការ", example: "The lock mechanism is broken.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "medical", meaning: "relating to medicine and health", meaningKh: "វេជ្ជសាស្ត្រ", example: "She needs medical attention.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "memory", meaning: "the ability to remember", meaningKh: "ការចងចាំ", example: "She has a good memory.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "mental", meaning: "of the mind", meaningKh: "ផ្លូវចិត្ត", example: "Mental health is important.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "merchant", meaning: "a person who trades goods", meaningKh: "ឈ្មួញ", example: "He's a coffee merchant.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "military", meaning: "of the armed forces", meaningKh: "យោធា", example: "He joined the military.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "minister", meaning: "a senior government official", meaningKh: "រដ្ឋមន្ត្រី", example: "The minister gave a speech.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "minority", meaning: "the smaller part of a group", meaningKh: "ភាគតិច", example: "A minority disagreed.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "mission", meaning: "an important assigned task", meaningKh: "បេសកកម្ម", example: "Their mission was to find water.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "mixture", meaning: "a combination of things", meaningKh: "ល្បាយ", example: "Stir the mixture well.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "moral", meaning: "relating to right behavior", meaningKh: "សីលធម៌", example: "He's a moral person.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "motivation", meaning: "the reason for doing something", meaningKh: "ការលើកទឹកចិត្ត", example: "Her motivation is to help others.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "mysterious", meaning: "difficult to understand or explain", meaningKh: "អាថ៌កំបាំង", example: "She had a mysterious smile.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "nervous", meaning: "worried or anxious", meaningKh: "ភ័យបារម្ភ", example: "I get nervous before exams.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "novel", meaning: "a long fictional book", meaningKh: "ប្រលោមលោក", example: "She wrote a romantic novel.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "offense", meaning: "an action that breaks a rule", meaningKh: "ការប្រមាថ", example: "Speeding is a minor offense.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "operate", meaning: "to work or function", meaningKh: "ដំណើរការ", example: "This machine operates by remote control.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "ordinary", meaning: "usual; not special", meaningKh: "ធម្មតា", example: "It was just an ordinary day.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "overall", meaning: "in general; considering everything", meaningKh: "សរុបទៅ", example: "Overall, the project was a success.", partOfSpeech: "adverb", level: Level.INTERMEDIATE },
  { word: "passenger", meaning: "a person traveling in a vehicle", meaningKh: "អ្នកដំណើរ", example: "The bus carried twenty passengers.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "payment", meaning: "money paid", meaningKh: "ការទូទាត់", example: "Cash payment is preferred.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "peaceful", meaning: "calm and quiet", meaningKh: "ស្ងប់", example: "It's a peaceful village.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "percentage", meaning: "a rate or amount per hundred", meaningKh: "ភាគរយ", example: "A high percentage agreed.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "personality", meaning: "qualities that make someone unique", meaningKh: "បុគ្គលិកលក្ខណៈ", example: "She has a strong personality.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "phenomenon", meaning: "an observable event or fact", meaningKh: "បាតុភូត", example: "A rainbow is a natural phenomenon.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "pleasure", meaning: "a feeling of happiness", meaningKh: "ការសប្បាយរីករាយ", example: "It's a pleasure to meet you.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "political", meaning: "relating to politics", meaningKh: "នយោបាយ", example: "She has political ambitions.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "population", meaning: "all people in an area", meaningKh: "ប្រជាជន", example: "The city has a large population.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "powerful", meaning: "having great power or influence", meaningKh: "មានអំណាច", example: "He gave a powerful speech.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "precise", meaning: "exact and accurate", meaningKh: "ច្បាស់លាស់", example: "Give me the precise time.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "presence", meaning: "the state of being present", meaningKh: "វត្តមាន", example: "Your presence is required.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "privacy", meaning: "freedom from being watched", meaningKh: "ភាពឯកជន", example: "She values her privacy.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "proper", meaning: "correct or appropriate", meaningKh: "សមរម្យ", example: "Wear proper clothes for the meeting.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "property", meaning: "things owned", meaningKh: "ទ្រព្យសម្បត្តិ", example: "This is private property.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "proposal", meaning: "a plan put forward", meaningKh: "សំណើ", example: "She made an interesting proposal.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "publication", meaning: "the act of publishing; a published work", meaningKh: "ការបោះពុម្ពផ្សាយ", example: "The publication date is May 1.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
];
