import { Level } from "@prisma/client";
import type { VocabEntry } from "./types";

/** ~300 real B1 (intermediate) English vocabulary words. */
export const intermediateB1Vocab: VocabEntry[] = [
  // ===== A =====
  { word: "abandon", meaning: "to leave behind permanently", meaningKh: "បោះបង់", example: "They had to abandon the car.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "absorb", meaning: "to soak up; to take in", meaningKh: "ស្រូបយក", example: "The sponge absorbs water quickly.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "academic", meaning: "relating to schools and study", meaningKh: "ការសិក្សា", example: "She has strong academic skills.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "achieve", meaning: "to successfully complete something", meaningKh: "សម្រេច", example: "She achieved her goal.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "acknowledge", meaning: "to accept or admit", meaningKh: "ទទួលស្គាល់", example: "He acknowledged his mistake.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "acquire", meaning: "to get or obtain", meaningKh: "ទទួលបាន", example: "He acquired new skills at work.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "adapt", meaning: "to change to fit new conditions", meaningKh: "សម្របខ្លួន", example: "Children adapt quickly to new schools.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "adequate", meaning: "good enough; sufficient", meaningKh: "គ្រប់គ្រាន់", example: "We have adequate supplies for the trip.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "adjust", meaning: "to make small changes", meaningKh: "កែតម្រូវ", example: "Adjust your seat before driving.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "admire", meaning: "to look at with respect", meaningKh: "កោតសរសើរ", example: "I admire her courage.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "admit", meaning: "to confess; to allow to enter", meaningKh: "សារភាព", example: "He admitted he was wrong.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "afford", meaning: "to have enough money for", meaningKh: "មានលទ្ធភាព", example: "I can't afford a new car.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "agency", meaning: "an organization providing a service", meaningKh: "ភ្នាក់ងារ", example: "She works for a travel agency.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "ambitious", meaning: "having a strong desire to succeed", meaningKh: "មានមហិច្ឆតា", example: "She is an ambitious young woman.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "analyze", meaning: "to examine in detail", meaningKh: "វិភាគ", example: "Scientists analyze the data carefully.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "annoy", meaning: "to bother or irritate", meaningKh: "ធ្វើឱ្យរំខាន", example: "The loud noise annoys me.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "annual", meaning: "happening once a year", meaningKh: "ប្រចាំឆ្នាំ", example: "Our annual meeting is in June.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "anxiety", meaning: "a feeling of worry", meaningKh: "ការថប់បារម្ភ", example: "He suffers from anxiety before tests.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "anxious", meaning: "worried or nervous", meaningKh: "ថប់បារម្ភ", example: "I'm anxious about the interview.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "appeal", meaning: "to make an earnest request", meaningKh: "ទាក់ទាញ", example: "The charity appealed for donations.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "applicant", meaning: "a person who applies", meaningKh: "បេក្ខជន", example: "We received many applicants.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "appoint", meaning: "to choose for a position", meaningKh: "តែងតាំង", example: "She was appointed manager.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "appreciate", meaning: "to feel grateful for", meaningKh: "កោតសរសើរ", example: "I appreciate your help.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "appropriate", meaning: "suitable for the situation", meaningKh: "សមរម្យ", example: "That's not appropriate behavior.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "approve", meaning: "to officially agree to", meaningKh: "យល់ព្រម", example: "The boss approved my plan.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "argument", meaning: "a disagreement; a reason given", meaningKh: "ការឈ្លោះប្រកែក", example: "They had an argument about money.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "arise", meaning: "to come into being", meaningKh: "កើតឡើង", example: "Problems can arise unexpectedly.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "ashamed", meaning: "feeling embarrassed", meaningKh: "ខ្មាសអៀន", example: "He was ashamed of his behavior.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "aspect", meaning: "a particular part or feature", meaningKh: "ផ្នែក", example: "Every aspect of the plan must be checked.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "assemble", meaning: "to put together", meaningKh: "ប្រមូលផ្តុំ", example: "Workers assemble cars at the factory.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "assess", meaning: "to evaluate; to judge", meaningKh: "វាយតម្លៃ", example: "The teacher will assess our work.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "assign", meaning: "to give a task", meaningKh: "ប្រគល់ភារកិច្ច", example: "She assigned us a project.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "assist", meaning: "to help", meaningKh: "ជួយ", example: "He assisted the elderly woman.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "assume", meaning: "to suppose without proof", meaningKh: "សន្មត", example: "I assumed you knew the answer.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "athlete", meaning: "a person trained in sports", meaningKh: "កីឡាករ", example: "She is a famous athlete.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "atmosphere", meaning: "the air around Earth; mood of a place", meaningKh: "បរិយាកាស", example: "The restaurant has a friendly atmosphere.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "attach", meaning: "to fasten or connect", meaningKh: "ភ្ជាប់", example: "Please attach a photo to your application.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "attitude", meaning: "a way of thinking or feeling", meaningKh: "អាកប្បកិរិយា", example: "She has a positive attitude.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "audience", meaning: "people watching or listening", meaningKh: "ទស្សនិកជន", example: "The audience clapped loudly.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "authority", meaning: "the power to give orders", meaningKh: "អំណាច", example: "She has the authority to decide.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "aware", meaning: "knowing about something", meaningKh: "ដឹង", example: "Are you aware of the risks?", partOfSpeech: "adjective", level: Level.INTERMEDIATE },

  // ===== B =====
  { word: "barrier", meaning: "something that blocks the way", meaningKh: "ឧបសគ្គ", example: "Language is a barrier to communication.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "behave", meaning: "to act in a particular way", meaningKh: "ប្រព្រឹត្ត", example: "The children behaved well at school.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "beneath", meaning: "in or to a lower position", meaningKh: "ខាងក្រោម", example: "The treasure lay beneath the ground.", partOfSpeech: "preposition", level: Level.INTERMEDIATE },
  { word: "biography", meaning: "a written account of a life", meaningKh: "ជីវប្រវត្តិ", example: "I read a biography of Einstein.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "boost", meaning: "to increase or improve", meaningKh: "ជំរុញ", example: "The win boosted his confidence.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "bother", meaning: "to annoy or trouble", meaningKh: "រំខាន", example: "Don't bother him; he's busy.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "brief", meaning: "lasting a short time", meaningKh: "សង្ខេប", example: "He gave a brief speech.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "brilliant", meaning: "extremely clever or bright", meaningKh: "ឆ្នើម", example: "She is a brilliant student.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "browse", meaning: "to look through casually", meaningKh: "រកមើល", example: "I like to browse online shops.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "budget", meaning: "a plan for spending money", meaningKh: "ថវិកា", example: "We must stay within our budget.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "bully", meaning: "to frighten or hurt a weaker person", meaningKh: "ខ្លាំងបង្ខំ", example: "He was bullied at school.", partOfSpeech: "verb", level: Level.INTERMEDIATE },

  // ===== C =====
  { word: "campaign", meaning: "an organized effort", meaningKh: "យុទ្ធនាការ", example: "The campaign raised millions for charity.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "candidate", meaning: "a person seeking a position", meaningKh: "បេក្ខជន", example: "There are five candidates for the job.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "capable", meaning: "able to do something", meaningKh: "មានសមត្ថភាព", example: "She is capable of great things.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "capacity", meaning: "the ability to hold or contain", meaningKh: "សមត្ថភាព", example: "The stadium has a capacity of 50,000.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "category", meaning: "a class or group", meaningKh: "ប្រភេទ", example: "Books are arranged by category.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "ceremony", meaning: "a formal event", meaningKh: "ពិធី", example: "The wedding ceremony was beautiful.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "charity", meaning: "giving help to those in need", meaningKh: "សប្បុរសធម៌", example: "She donated to charity.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "cheat", meaning: "to act dishonestly", meaningKh: "បន្លំ", example: "Don't cheat on the exam.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "claim", meaning: "to assert as true", meaningKh: "អះអាង", example: "He claims to have seen a ghost.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "client", meaning: "a customer of a service", meaningKh: "អតិថិជន", example: "The lawyer met with her client.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "colleague", meaning: "a person you work with", meaningKh: "សហការី", example: "My colleagues are very supportive.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "combine", meaning: "to mix together", meaningKh: "បញ្ចូលគ្នា", example: "Combine the flour and sugar.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "comment", meaning: "a remark or opinion", meaningKh: "មតិយោបល់", example: "She made a comment about the food.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "commit", meaning: "to pledge or do", meaningKh: "ប្តេជ្ញាចិត្ត", example: "He committed to working hard.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "compete", meaning: "to try to win against others", meaningKh: "ប្រកួត", example: "Many teams will compete in the finals.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "complain", meaning: "to express dissatisfaction", meaningKh: "ត្អូញត្អែរ", example: "She complained about the cold weather.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "complex", meaning: "complicated; not simple", meaningKh: "ស្មុគស្មាញ", example: "This is a complex problem.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "complicated", meaning: "difficult to understand", meaningKh: "ស្មុគស្មាញ", example: "The instructions are complicated.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "compromise", meaning: "an agreement reached by both sides", meaningKh: "សម្របសម្រួល", example: "Marriage requires compromise.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "concentrate", meaning: "to focus attention", meaningKh: "ផ្តោតអារម្មណ៍", example: "I can't concentrate with the TV on.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "concept", meaning: "an idea or principle", meaningKh: "គំនិត", example: "The concept of freedom is important.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "concerned", meaning: "worried", meaningKh: "ខ្វល់ខ្វាយ", example: "I'm concerned about your health.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "conclude", meaning: "to come to an end; to decide", meaningKh: "សន្និដ្ឋាន", example: "She concluded the meeting at noon.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "conduct", meaning: "to lead or direct; behavior", meaningKh: "ដឹកនាំ", example: "He will conduct the orchestra.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "confess", meaning: "to admit truthfully", meaningKh: "សារភាព", example: "He confessed to the crime.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "confidence", meaning: "belief in oneself", meaningKh: "ទំនុកចិត្ត", example: "She speaks with confidence.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "confirm", meaning: "to make certain", meaningKh: "បញ្ជាក់", example: "Please confirm your booking.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "conflict", meaning: "a serious disagreement", meaningKh: "ជម្លោះ", example: "There was a conflict between the two groups.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "confuse", meaning: "to make unclear", meaningKh: "ច្រឡំ", example: "The directions confused me.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "consequence", meaning: "a result of an action", meaningKh: "ផលវិបាក", example: "Every action has consequences.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "consider", meaning: "to think carefully about", meaningKh: "ពិចារណា", example: "Please consider my offer.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "consist", meaning: "to be made up of", meaningKh: "មានសមាសភាគ", example: "Water consists of hydrogen and oxygen.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "constant", meaning: "happening all the time", meaningKh: "ឥតឈប់ឈរ", example: "She lives with constant pain.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "construct", meaning: "to build", meaningKh: "សាងសង់", example: "They will construct a new bridge.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "consult", meaning: "to seek advice", meaningKh: "ពិគ្រោះ", example: "Consult your doctor before taking it.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "consume", meaning: "to eat or use up", meaningKh: "ប្រើប្រាស់", example: "He consumes too much sugar.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "contain", meaning: "to have inside", meaningKh: "មាន", example: "The box contains old letters.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "contemporary", meaning: "of the present time", meaningKh: "សម័យបច្ចុប្បន្ន", example: "I prefer contemporary art.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "content", meaning: "what is inside; satisfied", meaningKh: "មាតិកា", example: "Read the table of contents.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "context", meaning: "background of a situation", meaningKh: "បរិបទ", example: "Words have meanings in context.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "contract", meaning: "a written agreement", meaningKh: "កិច្ចសន្យា", example: "She signed a two-year contract.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "contrast", meaning: "a clear difference", meaningKh: "ភាពផ្ទុយគ្នា", example: "There's a sharp contrast between them.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "contribute", meaning: "to give a part", meaningKh: "រួមចំណែក", example: "Everyone contributed to the gift.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "convenient", meaning: "easy to use", meaningKh: "ងាយស្រួល", example: "Online shopping is very convenient.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "convince", meaning: "to make someone believe", meaningKh: "បញ្ចុះបញ្ចូល", example: "He convinced me to come.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "cooperate", meaning: "to work together", meaningKh: "សហប្រតិបត្តិការ", example: "We must cooperate to finish on time.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "cope", meaning: "to deal with difficulties", meaningKh: "ដោះស្រាយ", example: "She copes well with stress.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "corporate", meaning: "of a large company", meaningKh: "សាជីវកម្ម", example: "He works in corporate finance.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "courage", meaning: "ability to face fear", meaningKh: "ភាពក្លាហាន", example: "It takes courage to speak up.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "criticize", meaning: "to find fault with", meaningKh: "រិះគន់", example: "Don't criticize without thinking.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "crowded", meaning: "full of people", meaningKh: "កុះករ", example: "The bus was crowded this morning.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "crucial", meaning: "extremely important", meaningKh: "សំខាន់បំផុត", example: "It is crucial to be honest.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "cruel", meaning: "causing pain on purpose", meaningKh: "ឃោរឃៅ", example: "Cruel words can hurt deeply.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "cure", meaning: "to make a sick person well", meaningKh: "ព្យាបាល", example: "Doctors are trying to cure the disease.", partOfSpeech: "verb", level: Level.INTERMEDIATE },

  // ===== D =====
  { word: "debate", meaning: "a formal discussion", meaningKh: "ការជជែកវែកញែក", example: "We had a debate about climate change.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "decent", meaning: "of acceptable quality", meaningKh: "សមរម្យ", example: "He earns a decent salary.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "declare", meaning: "to announce officially", meaningKh: "ប្រកាស", example: "The judge declared him innocent.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "decline", meaning: "to politely refuse; to decrease", meaningKh: "បដិសេធ", example: "She declined his invitation.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "decorate", meaning: "to make pretty", meaningKh: "តុបតែង", example: "They decorated the room for the party.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "decrease", meaning: "to make smaller", meaningKh: "ថយចុះ", example: "Sales decreased this year.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "dedicate", meaning: "to give time and effort to", meaningKh: "លះបង់", example: "She dedicated her life to teaching.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "define", meaning: "to explain the meaning of", meaningKh: "កំណត់និយមន័យ", example: "Can you define this word?", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "delay", meaning: "to postpone or be slow", meaningKh: "ពន្យារពេល", example: "The flight was delayed by fog.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "delicate", meaning: "easily broken or harmed", meaningKh: "ផុយស្រួយ", example: "Be careful; this glass is delicate.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "demand", meaning: "to ask forcefully", meaningKh: "ទាមទារ", example: "The workers demanded higher pay.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "demonstrate", meaning: "to show clearly", meaningKh: "បង្ហាញ", example: "Let me demonstrate how it works.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "depart", meaning: "to leave a place", meaningKh: "ចាកចេញ", example: "The train departs at 8 a.m.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "describe", meaning: "to say what something is like", meaningKh: "ពិពណ៌នា", example: "Describe your hometown.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "deserve", meaning: "to be worthy of", meaningKh: "សក្តិសម", example: "You deserve a reward.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "destination", meaning: "the place you are going to", meaningKh: "គោលដៅ", example: "Paris is a popular destination.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "determine", meaning: "to decide firmly", meaningKh: "កំណត់", example: "We need to determine the cause.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "device", meaning: "a piece of equipment", meaningKh: "ឧបករណ៍", example: "A phone is a useful device.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "diet", meaning: "the food a person eats", meaningKh: "របបអាហារ", example: "She follows a healthy diet.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "differ", meaning: "to be unlike", meaningKh: "ខុសគ្នា", example: "Our opinions differ on this matter.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "disappoint", meaning: "to fail to meet expectations", meaningKh: "ធ្វើឱ្យខកចិត្ត", example: "Don't disappoint your parents.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "discipline", meaning: "training to behave well", meaningKh: "វិន័យ", example: "Self-discipline is important.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "display", meaning: "to show publicly", meaningKh: "បង្ហាញ", example: "The store displays new clothes.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "dispute", meaning: "an argument", meaningKh: "ការជម្លោះ", example: "There is a dispute over the land.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "distance", meaning: "the space between things", meaningKh: "ចម្ងាយ", example: "The distance to the city is 10 km.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "distinguish", meaning: "to tell apart", meaningKh: "បែងចែក", example: "Can you distinguish red from green?", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "distribute", meaning: "to give out to many", meaningKh: "ចែកចាយ", example: "They distribute food to the poor.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "disturb", meaning: "to interrupt or worry", meaningKh: "រំខាន", example: "Please don't disturb me while I work.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "diverse", meaning: "very varied", meaningKh: "ចម្រុះ", example: "We live in a diverse community.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "document", meaning: "an official paper", meaningKh: "ឯកសារ", example: "Sign the document, please.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "domestic", meaning: "of the home or country", meaningKh: "ក្នុងស្រុក", example: "Domestic flights are cheaper.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "donate", meaning: "to give freely", meaningKh: "បរិច្ចាគ", example: "She donated blood at the hospital.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "drown", meaning: "to die from being underwater", meaningKh: "លង់ទឹក", example: "Many people drown each year.", partOfSpeech: "verb", level: Level.INTERMEDIATE },

  // ===== E =====
  { word: "earn", meaning: "to get money by working", meaningKh: "រកប្រាក់", example: "She earns a high salary.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "economy", meaning: "the financial system", meaningKh: "សេដ្ឋកិច្ច", example: "The economy is growing.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "efficient", meaning: "working well without waste", meaningKh: "មានប្រសិទ្ធភាព", example: "She is an efficient worker.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "elect", meaning: "to choose by voting", meaningKh: "បោះឆ្នោតជ្រើសរើស", example: "They elected a new president.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "eliminate", meaning: "to completely remove", meaningKh: "លុបបំបាត់", example: "We must eliminate the danger.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "embarrass", meaning: "to make ashamed", meaningKh: "ធ្វើឱ្យអាម៉ាស់", example: "You're embarrassing me.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "embrace", meaning: "to hug; to accept gladly", meaningKh: "ឱប", example: "She embraced her son tightly.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "emerge", meaning: "to come out", meaningKh: "លេចចេញ", example: "The sun emerged from the clouds.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "emergency", meaning: "a serious unexpected event", meaningKh: "អាសន្ន", example: "Call 911 in an emergency.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "emphasize", meaning: "to give special importance to", meaningKh: "បញ្ជាក់", example: "She emphasized the need for study.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "enable", meaning: "to make possible", meaningKh: "អនុញ្ញាតឱ្យ", example: "Money enables you to travel.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "encounter", meaning: "to meet unexpectedly", meaningKh: "ជួប", example: "We encountered a snake on the trail.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "encourage", meaning: "to give support", meaningKh: "លើកទឹកចិត្ត", example: "Parents should encourage their kids.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "endure", meaning: "to suffer patiently; to last", meaningKh: "ស៊ូទ្រាំ", example: "She endured years of pain.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "engage", meaning: "to involve someone", meaningKh: "ចូលរួម", example: "Good teachers engage their students.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "enhance", meaning: "to improve", meaningKh: "ពង្រឹង", example: "Exercise enhances your mood.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "enormous", meaning: "very large", meaningKh: "ធំធេង", example: "An enormous truck blocked the road.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "enthusiasm", meaning: "great excitement", meaningKh: "ការរីករាយ", example: "She showed great enthusiasm.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "essential", meaning: "absolutely necessary", meaningKh: "ចាំបាច់", example: "Water is essential for life.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "establish", meaning: "to set up; to start", meaningKh: "បង្កើត", example: "The company was established in 1990.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "estimate", meaning: "to roughly calculate", meaningKh: "ប៉ាន់ស្មាន", example: "I estimate it will cost $100.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "evaluate", meaning: "to judge the value of", meaningKh: "វាយតម្លៃ", example: "The teacher evaluated our essays.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "eventual", meaning: "happening at last", meaningKh: "ចុងបញ្ចប់", example: "Our eventual goal is success.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "exceed", meaning: "to go beyond", meaningKh: "លើស", example: "Don't exceed the speed limit.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "excellent", meaning: "extremely good", meaningKh: "ល្អប្រសើរ", example: "The food was excellent.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "exchange", meaning: "to give and receive", meaningKh: "ប្តូរ", example: "We exchanged phone numbers.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "exclude", meaning: "to keep out", meaningKh: "ដកចេញ", example: "Tax is excluded from the price.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "executive", meaning: "a senior manager", meaningKh: "ប្រធានប្រតិបត្តិ", example: "She is a top executive.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "exhibit", meaning: "to display publicly", meaningKh: "តាំងពិពណ៌", example: "The museum exhibits ancient art.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "expand", meaning: "to grow larger", meaningKh: "ពង្រីក", example: "The company plans to expand.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "expense", meaning: "money spent", meaningKh: "ការចំណាយ", example: "Travel expenses are high.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "experiment", meaning: "a scientific test", meaningKh: "ការពិសោធន៍", example: "We did an experiment in chemistry.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "explain", meaning: "to make clear", meaningKh: "ពន្យល់", example: "Please explain the rules.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "explore", meaning: "to travel and discover", meaningKh: "ស្វែងយល់", example: "Let's explore the new city.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "express", meaning: "to communicate feelings", meaningKh: "បង្ហាញ", example: "She expressed her thanks.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "extend", meaning: "to make longer", meaningKh: "ពន្យាយ", example: "Can you extend the deadline?", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "external", meaning: "on the outside", meaningKh: "ខាងក្រៅ", example: "Apply the cream externally.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "extreme", meaning: "very great in degree", meaningKh: "ខ្លាំងបំផុត", example: "He's an extreme sports fan.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },

  // ===== F =====
  { word: "facility", meaning: "a building or service for a purpose", meaningKh: "កន្លែងសម្រាប់សកម្មភាព", example: "The hotel has sports facilities.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "factor", meaning: "something that influences a result", meaningKh: "កត្តា", example: "Weather is a factor in farming.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "familiar", meaning: "well known", meaningKh: "ស្គាល់", example: "Her face looks familiar.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "fascinate", meaning: "to interest greatly", meaningKh: "ទាក់ទាញចំណាប់អារម្មណ៍", example: "Space fascinates me.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "feature", meaning: "a typical quality or part", meaningKh: "លក្ខណៈពិសេស", example: "The phone has many new features.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "flexible", meaning: "able to bend or change", meaningKh: "បត់បែន", example: "My schedule is flexible.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "fluent", meaning: "able to speak smoothly", meaningKh: "ស្ទាត់ជំនាញ", example: "She is fluent in three languages.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "focus", meaning: "to direct attention", meaningKh: "ផ្តោតអារម្មណ៍", example: "Focus on your studies.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "forecast", meaning: "a prediction about the future", meaningKh: "ការព្យាករណ៍", example: "The weather forecast says rain.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "foreign", meaning: "from another country", meaningKh: "បរទេស", example: "She speaks several foreign languages.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "formal", meaning: "following rules and customs", meaningKh: "ផ្លូវការ", example: "Wear a formal suit to the meeting.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "former", meaning: "from an earlier time", meaningKh: "អតីត", example: "He is a former teacher.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "fortunate", meaning: "lucky", meaningKh: "សំណាងល្អ", example: "I'm fortunate to have such friends.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "frequent", meaning: "happening often", meaningKh: "ញឹកញាប់", example: "He is a frequent visitor.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "frighten", meaning: "to make afraid", meaningKh: "បំភ័យ", example: "The thunder frightened the dog.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "frustrate", meaning: "to prevent success", meaningKh: "ធ្វើឱ្យតប់ប្រមល់", example: "Traffic frustrates me daily.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "fulfill", meaning: "to satisfy or complete", meaningKh: "បំពេញ", example: "She fulfilled her promise.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "fund", meaning: "money set aside", meaningKh: "មូលនិធិ", example: "They raised funds for charity.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "fundamental", meaning: "basic and important", meaningKh: "ជាមូលដ្ឋាន", example: "Honesty is a fundamental value.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "furious", meaning: "extremely angry", meaningKh: "ខឹងជាខ្លាំង", example: "Dad was furious about the broken vase.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "furniture", meaning: "tables, chairs, beds, etc.", meaningKh: "គ្រឿងសង្ហារឹម", example: "We bought new furniture.", partOfSpeech: "noun", level: Level.INTERMEDIATE },

  // ===== G =====
  { word: "gender", meaning: "the state of being male or female", meaningKh: "ភេទ", example: "Pay should not depend on gender.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "generate", meaning: "to produce", meaningKh: "បង្កើត", example: "Wind turbines generate electricity.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "generous", meaning: "giving freely", meaningKh: "សប្បុរស", example: "She is generous with her time.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "genuine", meaning: "real; sincere", meaningKh: "ពិតប្រាកដ", example: "He showed genuine kindness.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "gesture", meaning: "a movement of the body", meaningKh: "កាយវិការ", example: "She waved as a friendly gesture.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "global", meaning: "of the whole world", meaningKh: "សកល", example: "Climate change is a global issue.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "govern", meaning: "to control or rule", meaningKh: "គ្រប់គ្រង", example: "The party governs the country.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "gradual", meaning: "happening slowly", meaningKh: "បន្តិចម្តងៗ", example: "The improvement was gradual.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "grant", meaning: "to give officially; money given", meaningKh: "ផ្តល់ឱ្យ", example: "The university grants scholarships.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "grateful", meaning: "feeling thankful", meaningKh: "ដឹងគុណ", example: "I'm grateful for your help.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "greet", meaning: "to welcome", meaningKh: "ស្វាគមន៍", example: "She greeted us at the door.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "grief", meaning: "deep sadness", meaningKh: "សោកសៅ", example: "She felt great grief at his death.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "guarantee", meaning: "to promise as certain", meaningKh: "ធានា", example: "I guarantee you'll like it.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "guilt", meaning: "the feeling of having done wrong", meaningKh: "កំហុស", example: "He felt guilt over his lie.", partOfSpeech: "noun", level: Level.INTERMEDIATE },

  // ===== H =====
  { word: "harsh", meaning: "severe; unkind", meaningKh: "ឃោរឃៅ", example: "The winter is harsh in the north.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "healthy", meaning: "in good health", meaningKh: "មានសុខភាពល្អ", example: "Eat healthy food every day.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "heritage", meaning: "things passed down from the past", meaningKh: "បេតិកភណ្ឌ", example: "Cambodian heritage is rich.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "hesitate", meaning: "to pause before acting", meaningKh: "ស្ទាក់ស្ទើរ", example: "Don't hesitate to ask questions.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "highlight", meaning: "to draw attention to", meaningKh: "បញ្ជាក់", example: "Highlight the important words.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "hire", meaning: "to employ someone", meaningKh: "ជួល", example: "We need to hire a new accountant.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "honest", meaning: "telling the truth", meaningKh: "ស្មោះត្រង់", example: "Always be honest with your friends.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "honor", meaning: "respect; to respect", meaningKh: "កិត្តិយស", example: "It's an honor to meet you.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "household", meaning: "all people in a home", meaningKh: "គ្រួសារ", example: "Most households have a TV.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "humor", meaning: "what makes things funny", meaningKh: "ការកំប្លែង", example: "She has a great sense of humor.", partOfSpeech: "noun", level: Level.INTERMEDIATE },

  // ===== I =====
  { word: "illegal", meaning: "against the law", meaningKh: "ខុសច្បាប់", example: "It is illegal to drive without a license.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "illness", meaning: "a state of being sick", meaningKh: "ជំងឺ", example: "He missed school due to illness.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "illustrate", meaning: "to show with pictures or examples", meaningKh: "បង្ហាញដោយរូបភាព", example: "She illustrated the story with photos.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "imitate", meaning: "to copy someone", meaningKh: "ធ្វើតាម", example: "Children imitate their parents.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "immediate", meaning: "happening at once", meaningKh: "ភ្លាមៗ", example: "I need an immediate answer.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "implement", meaning: "to put into action", meaningKh: "អនុវត្ត", example: "We will implement the new plan.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "imply", meaning: "to suggest indirectly", meaningKh: "បញ្ជាក់ដោយប្រយោល", example: "Her silence implied agreement.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "impress", meaning: "to cause admiration", meaningKh: "ចាប់អារម្មណ៍", example: "Her speech impressed everyone.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "incident", meaning: "an event, often unpleasant", meaningKh: "ឧប្បត្តិហេតុ", example: "The incident was reported to police.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "income", meaning: "money received", meaningKh: "ប្រាក់ចំណូល", example: "His monthly income is $500.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "individual", meaning: "a single person", meaningKh: "បុគ្គល", example: "Each individual has rights.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "inevitable", meaning: "certain to happen", meaningKh: "ជៀសមិនរួច", example: "Change is inevitable.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "influence", meaning: "the power to affect", meaningKh: "ឥទ្ធិពល", example: "Parents have great influence on children.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "ingredient", meaning: "a part of a mixture", meaningKh: "គ្រឿងផ្សំ", example: "Sugar is the main ingredient.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "inherit", meaning: "to receive from a relative", meaningKh: "ទទួលមរតក", example: "He inherited the house from his uncle.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "initial", meaning: "happening at the beginning", meaningKh: "ដំបូង", example: "My initial reaction was surprise.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "initiative", meaning: "the ability to start things", meaningKh: "គំនិតផ្តួចផ្តើម", example: "She showed great initiative.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "innocent", meaning: "not guilty", meaningKh: "ស្លូតត្រង់", example: "The court found him innocent.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "innovation", meaning: "a new idea or method", meaningKh: "នវានុវត្តន៍", example: "Technology brings innovation.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "insight", meaning: "deep understanding", meaningKh: "ការយល់ដឹងស៊ីជម្រៅ", example: "Her book gives great insight.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "inspire", meaning: "to give creative ideas", meaningKh: "បំផុសគំនិត", example: "Her story inspired me.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "install", meaning: "to put in place", meaningKh: "ដំឡើង", example: "Please install the new software.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "instance", meaning: "an example or case", meaningKh: "ករណី", example: "There were many instances of fraud.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "instant", meaning: "happening at once", meaningKh: "ភ្លាមៗ", example: "The movie was an instant hit.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "instead", meaning: "in place of", meaningKh: "ជំនួសវិញ", example: "Take the train instead of the bus.", partOfSpeech: "adverb", level: Level.INTERMEDIATE },
  { word: "instinct", meaning: "natural ability or feeling", meaningKh: "ភាពច្នៃប្រឌិតធម្មជាតិ", example: "Birds know to fly south by instinct.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "intelligent", meaning: "showing high mental ability", meaningKh: "ឆ្លាត", example: "She is an intelligent student.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "intend", meaning: "to plan to do", meaningKh: "មានបំណង", example: "I intend to study harder.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "intense", meaning: "very strong", meaningKh: "ខ្លាំងក្លា", example: "The heat is intense today.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "interact", meaning: "to communicate with", meaningKh: "ទំនាក់ទំនង", example: "Children interact through play.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "interfere", meaning: "to get involved in others' affairs", meaningKh: "ជ្រៀតជ្រែក", example: "Don't interfere in my business.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "interpret", meaning: "to explain the meaning of", meaningKh: "បកប្រែ", example: "How do you interpret this poem?", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "interrupt", meaning: "to stop temporarily", meaningKh: "បំបែក", example: "Please don't interrupt me.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "intervene", meaning: "to step in", meaningKh: "អន្តរាគមន៍", example: "The teacher intervened in the fight.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "interview", meaning: "a formal meeting with questions", meaningKh: "ការសម្ភាស", example: "I have a job interview tomorrow.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "introduce", meaning: "to make known", meaningKh: "ណែនាំ", example: "Let me introduce my friend.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "invent", meaning: "to create something new", meaningKh: "បង្កើតថ្មី", example: "Edison invented the light bulb.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "invest", meaning: "to put money into something", meaningKh: "វិនិយោគ", example: "She invested in real estate.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "investigate", meaning: "to look into carefully", meaningKh: "ស៊ើបអង្កេត", example: "Police are investigating the crime.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "involve", meaning: "to include as a part", meaningKh: "ពាក់ព័ន្ធ", example: "The job involves teamwork.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "isolate", meaning: "to keep separate", meaningKh: "ដាច់ស្រយាល", example: "The patient was isolated.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "issue", meaning: "a problem to discuss", meaningKh: "បញ្ហា", example: "We need to discuss this issue.", partOfSpeech: "noun", level: Level.INTERMEDIATE },

  // ===== J =====
  { word: "joint", meaning: "shared by two or more", meaningKh: "រួមគ្នា", example: "They opened a joint bank account.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "justify", meaning: "to give a good reason for", meaningKh: "ដាក់ហេតុផល", example: "Can you justify your decision?", partOfSpeech: "verb", level: Level.INTERMEDIATE },

  // ===== L =====
  { word: "lack", meaning: "to be without", meaningKh: "ខ្វះ", example: "He lacks experience.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "landscape", meaning: "the view of an area of land", meaningKh: "ទេសភាព", example: "The landscape is beautiful here.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "latter", meaning: "the second of two", meaningKh: "ចុងក្រោយ", example: "I prefer the latter option.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "launch", meaning: "to start or send off", meaningKh: "ចាប់ផ្តើម", example: "They will launch the new product.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "lecture", meaning: "a formal talk on a topic", meaningKh: "បាឋកថា", example: "The lecture was very interesting.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "leisure", meaning: "free time", meaningKh: "ពេលទំនេរ", example: "What do you do in your leisure?", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "lend", meaning: "to let someone use temporarily", meaningKh: "ឱ្យខ្ចី", example: "Can you lend me a pen?", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "liberty", meaning: "freedom", meaningKh: "សេរីភាព", example: "Liberty is precious.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "lifestyle", meaning: "the way someone lives", meaningKh: "របៀបរស់នៅ", example: "Exercise leads to a healthy lifestyle.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "literature", meaning: "written works of art", meaningKh: "អក្សរសាស្ត្រ", example: "She studies English literature.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "loan", meaning: "money borrowed", meaningKh: "ប្រាក់កម្ចី", example: "I got a loan from the bank.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "locate", meaning: "to find the position of", meaningKh: "កំណត់ទីតាំង", example: "Can you locate the city on a map?", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "logic", meaning: "the science of reasoning", meaningKh: "តក្កវិទ្យា", example: "There's no logic in his argument.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "loyal", meaning: "faithful", meaningKh: "ស្មោះត្រង់", example: "He is a loyal friend.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "luxury", meaning: "great comfort", meaningKh: "ភាពប្រណីត", example: "They live in luxury.", partOfSpeech: "noun", level: Level.INTERMEDIATE },

  // ===== M =====
  { word: "maintain", meaning: "to keep in good condition", meaningKh: "ថែទាំ", example: "Maintain your car regularly.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "majority", meaning: "the larger number", meaningKh: "ភាគច្រើន", example: "The majority voted yes.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "manage", meaning: "to be in charge of", meaningKh: "គ្រប់គ្រង", example: "She manages a team of ten.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "manner", meaning: "way of doing something", meaningKh: "របៀប", example: "Speak in a polite manner.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "manufacture", meaning: "to make in a factory", meaningKh: "ផលិត", example: "They manufacture cars.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "margin", meaning: "the edge; the difference", meaningKh: "គែម", example: "Leave a wide margin on the page.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "master", meaning: "to learn thoroughly", meaningKh: "ស្ទាត់ជំនាញ", example: "It takes years to master a language.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "maximum", meaning: "the greatest amount", meaningKh: "អតិបរមា", example: "The maximum speed is 100 km/h.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "mention", meaning: "to speak of briefly", meaningKh: "លើកឡើង", example: "She mentioned your name today.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "minimum", meaning: "the smallest amount", meaningKh: "អប្បបរមា", example: "The minimum wage is rising.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "miracle", meaning: "an amazing event", meaningKh: "អព្ភូតហេតុ", example: "It was a miracle she survived.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "modest", meaning: "humble; not boastful", meaningKh: "សុភាពរាបសារ", example: "He is modest about his success.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "modify", meaning: "to make small changes", meaningKh: "កែប្រែ", example: "We modified the design.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "monitor", meaning: "to watch and check", meaningKh: "តាមដាន", example: "Doctors monitor patients carefully.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "motivate", meaning: "to give a reason to act", meaningKh: "ជំរុញ", example: "Good teachers motivate students.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "multiple", meaning: "many; several", meaningKh: "ច្រើន", example: "She has multiple talents.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "mutual", meaning: "shared by both sides", meaningKh: "ទៅវិញទៅមក", example: "We have mutual respect.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "mystery", meaning: "something unexplained", meaningKh: "អាថ៌កំបាំង", example: "Her death remains a mystery.", partOfSpeech: "noun", level: Level.INTERMEDIATE },

  // ===== N =====
  { word: "negative", meaning: "bad; opposite of positive", meaningKh: "អវិជ្ជមាន", example: "Try to avoid negative thoughts.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "neglect", meaning: "to fail to care for", meaningKh: "មិនអើពើ", example: "Don't neglect your health.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "negotiate", meaning: "to discuss to reach agreement", meaningKh: "ចរចា", example: "They negotiated the price.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "nevertheless", meaning: "in spite of that", meaningKh: "ទោះជាយ៉ាងណាក៏ដោយ", example: "It rained; nevertheless, we went out.", partOfSpeech: "adverb", level: Level.INTERMEDIATE },
  { word: "notion", meaning: "an idea or belief", meaningKh: "គំនិត", example: "He had no notion of what to do.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "nuclear", meaning: "of atomic energy", meaningKh: "នុយក្លេអ៊ែរ", example: "Some countries use nuclear power.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "numerous", meaning: "many", meaningKh: "ជាច្រើន", example: "There are numerous examples.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },

  // ===== O =====
  { word: "observe", meaning: "to watch carefully", meaningKh: "សង្កេត", example: "Observe how the animal moves.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "obstacle", meaning: "something blocking the way", meaningKh: "ឧបសគ្គ", example: "She overcame many obstacles.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "occasion", meaning: "a particular event or time", meaningKh: "ឱកាស", example: "Wear a suit for the occasion.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "occupy", meaning: "to take up space", meaningKh: "កាន់កាប់", example: "The book occupies most of the shelf.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "offend", meaning: "to upset someone", meaningKh: "ធ្វើឱ្យប្រមាថ", example: "I didn't mean to offend you.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "opponent", meaning: "a person who competes against", meaningKh: "គូប្រកួត", example: "His opponent was a strong player.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "opportunity", meaning: "a favorable chance", meaningKh: "ឱកាស", example: "This is a great opportunity.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "oppose", meaning: "to disagree with", meaningKh: "ប្រឆាំង", example: "Many people oppose the new law.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "optimistic", meaning: "hopeful about the future", meaningKh: "សុទិដ្ឋិនិយម", example: "She is optimistic about her chances.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "organize", meaning: "to arrange or plan", meaningKh: "រៀបចំ", example: "She organized a birthday party.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "otherwise", meaning: "or else", meaningKh: "បើមិនដូច្នោះទេ", example: "Hurry, otherwise we'll be late.", partOfSpeech: "adverb", level: Level.INTERMEDIATE },
  { word: "outcome", meaning: "a result", meaningKh: "លទ្ធផល", example: "What was the outcome of the test?", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "output", meaning: "the amount produced", meaningKh: "ផលិតផល", example: "The factory's output is high.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "overcome", meaning: "to defeat or deal with", meaningKh: "យកឈ្នះ", example: "He overcame his fears.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "owe", meaning: "to need to pay or give back", meaningKh: "ជំពាក់", example: "I owe him fifty dollars.", partOfSpeech: "verb", level: Level.INTERMEDIATE },

  // ===== P =====
  { word: "panel", meaning: "a group of experts; a flat board", meaningKh: "ក្រុមអ្នកជំនាញ", example: "A panel of judges decided.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "panic", meaning: "sudden uncontrollable fear", meaningKh: "ភ័យតក់ស្លុត", example: "There was panic when the fire alarm rang.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "participate", meaning: "to take part in", meaningKh: "ចូលរួម", example: "Everyone should participate in class.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "particular", meaning: "specific", meaningKh: "ជាក់លាក់", example: "Is there a particular book you want?", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "passion", meaning: "very strong emotion", meaningKh: "ចំណង់ចំណូលចិត្ត", example: "Music is her passion.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "patient", meaning: "able to wait calmly", meaningKh: "អត់ធ្មត់", example: "Be patient with the children.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "peculiar", meaning: "strange or unusual", meaningKh: "ចម្លែក", example: "He has a peculiar way of talking.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "penalty", meaning: "a punishment", meaningKh: "ការផាក", example: "The penalty for speeding is a fine.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "perceive", meaning: "to notice or understand", meaningKh: "យល់ឃើញ", example: "I perceived a change in him.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "perform", meaning: "to do an action", meaningKh: "សម្តែង", example: "The band will perform tonight.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "permanent", meaning: "lasting forever", meaningKh: "អចិន្ត្រៃយ៍", example: "She has a permanent job.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "permit", meaning: "to allow", meaningKh: "អនុញ្ញាត", example: "Smoking is not permitted here.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "perspective", meaning: "a point of view", meaningKh: "ទស្សនៈ", example: "Try to see her perspective.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "persuade", meaning: "to convince to do", meaningKh: "បញ្ចុះបញ្ចូល", example: "She persuaded me to go.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "phase", meaning: "a stage of development", meaningKh: "ដំណាក់កាល", example: "We are in the planning phase.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "philosophy", meaning: "the study of ideas", meaningKh: "ទស្សនវិជ្ជា", example: "He studies philosophy at university.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "physical", meaning: "of the body", meaningKh: "ផ្នែករាងកាយ", example: "Daily physical exercise is good.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "pioneer", meaning: "the first to do something", meaningKh: "អ្នកត្រួសត្រាយ", example: "She was a pioneer in medicine.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "polite", meaning: "showing good manners", meaningKh: "សុភាព", example: "Always be polite to elders.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "pollution", meaning: "harmful substances in the environment", meaningKh: "ការបំពុល", example: "Air pollution is a serious problem.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "portion", meaning: "a part", meaningKh: "ចំណែក", example: "Give him a small portion.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "positive", meaning: "good; certain", meaningKh: "វិជ្ជមាន", example: "She has a positive attitude.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "possess", meaning: "to own", meaningKh: "មានកម្មសិទ្ធិ", example: "He possesses great talent.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "potential", meaning: "the possibility of being", meaningKh: "សក្តានុពល", example: "She has the potential to win.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "poverty", meaning: "the state of being poor", meaningKh: "ភាពក្រីក្រ", example: "Many people live in poverty.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "practical", meaning: "useful; sensible", meaningKh: "ជាក់ស្តែង", example: "Give me practical advice.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "praise", meaning: "to express approval", meaningKh: "សរសើរ", example: "The teacher praised her work.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "precious", meaning: "very valuable", meaningKh: "មានតម្លៃ", example: "Time is precious.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "predict", meaning: "to say in advance", meaningKh: "ព្យាករណ៍", example: "Can you predict the weather?", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "prefer", meaning: "to like more", meaningKh: "ចូលចិត្តជាង", example: "I prefer tea to coffee.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "preserve", meaning: "to keep in good condition", meaningKh: "រក្សា", example: "We should preserve nature.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "pressure", meaning: "force; stress", meaningKh: "សម្ពាធ", example: "She works well under pressure.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "pretend", meaning: "to act as if", meaningKh: "ធ្វើពុត", example: "Children pretend to be heroes.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "prevent", meaning: "to stop from happening", meaningKh: "ការពារ", example: "Wash your hands to prevent illness.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "previous", meaning: "happening before", meaningKh: "មុន", example: "She has previous experience.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "principle", meaning: "a basic truth or rule", meaningKh: "គោលការណ៍", example: "Honesty is a key principle.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "priority", meaning: "what comes first", meaningKh: "អាទិភាព", example: "Safety is our top priority.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "privilege", meaning: "a special right", meaningKh: "សិទ្ធិពិសេស", example: "It's a privilege to meet you.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "procedure", meaning: "a way of doing something", meaningKh: "នីតិវិធី", example: "Follow the safety procedure.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "process", meaning: "a series of actions", meaningKh: "ដំណើរការ", example: "Learning is a slow process.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "profession", meaning: "a job needing training", meaningKh: "វិជ្ជាជីវៈ", example: "Teaching is a noble profession.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "profit", meaning: "money gained", meaningKh: "ប្រាក់ចំណេញ", example: "The shop made a big profit.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "progress", meaning: "to move forward", meaningKh: "វឌ្ឍនភាព", example: "She is making good progress.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "promote", meaning: "to advance in rank; to support", meaningKh: "តម្លើងតួនាទី", example: "He was promoted to manager.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "proof", meaning: "evidence that shows truth", meaningKh: "ភស្តុតាង", example: "Do you have proof?", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "propose", meaning: "to suggest", meaningKh: "ស្នើ", example: "I propose a new plan.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "prospect", meaning: "the chance of success", meaningKh: "ការរំពឹងទុក", example: "The prospect of a job excites me.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "protest", meaning: "to object publicly", meaningKh: "ប្រឆាំង", example: "They protested against the law.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "prove", meaning: "to show as true", meaningKh: "បង្ហាញ", example: "Prove that you can do it.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "publish", meaning: "to make available to read", meaningKh: "បោះពុម្ព", example: "She publishes a new book yearly.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "punish", meaning: "to make pay for wrong", meaningKh: "ដាក់ទោស", example: "Don't punish him too harshly.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "purchase", meaning: "to buy", meaningKh: "ទិញ", example: "She purchased a new computer.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "pursue", meaning: "to chase or follow", meaningKh: "តាមដោះ", example: "Pursue your dreams.", partOfSpeech: "verb", level: Level.INTERMEDIATE },

  // ===== Q =====
  { word: "qualify", meaning: "to meet requirements", meaningKh: "មានគុណវុឌ្ឍិ", example: "Does she qualify for the loan?", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "quote", meaning: "to repeat exact words", meaningKh: "ដកស្រង់", example: "She quoted from his speech.", partOfSpeech: "verb", level: Level.INTERMEDIATE },

  // ===== R =====
  { word: "range", meaning: "the extent of variation", meaningKh: "ជួរ", example: "The shop has a wide range of shoes.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "rational", meaning: "based on reason", meaningKh: "សមហេតុផល", example: "Make a rational decision.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "raw", meaning: "not cooked or processed", meaningKh: "ឆៅ", example: "I don't eat raw fish.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "reasonable", meaning: "fair and sensible", meaningKh: "សមហេតុផល", example: "He made a reasonable offer.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "recall", meaning: "to remember", meaningKh: "ចងចាំ", example: "I can't recall his name.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "recommend", meaning: "to suggest as good", meaningKh: "ផ្តល់អនុសាសន៍", example: "I recommend this restaurant.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "recover", meaning: "to get better", meaningKh: "ស្តារឡើងវិញ", example: "She recovered from the flu.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "refer", meaning: "to mention", meaningKh: "យោង", example: "Refer to page ten.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "reflect", meaning: "to think carefully; to mirror", meaningKh: "ឆ្លុះបញ្ចាំង", example: "Reflect on your actions.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "reform", meaning: "to change for the better", meaningKh: "កែទម្រង់", example: "Education needs reform.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "refuse", meaning: "to say no", meaningKh: "បដិសេធ", example: "He refused my offer.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "regard", meaning: "to consider", meaningKh: "ចាត់ទុក", example: "I regard him as a friend.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "region", meaning: "an area of a country", meaningKh: "តំបន់", example: "This region grows rice.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "register", meaning: "to put on an official list", meaningKh: "ចុះឈ្មោះ", example: "Please register for the course.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "regret", meaning: "to feel sorry about", meaningKh: "សោកស្តាយ", example: "I regret what I said.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "regular", meaning: "happening often; normal", meaningKh: "ទៀងទាត់", example: "She does regular exercise.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "reject", meaning: "to refuse to accept", meaningKh: "បដិសេធ", example: "They rejected my application.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "relate", meaning: "to connect; to tell", meaningKh: "ទាក់ទង", example: "Can you relate this to your job?", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "release", meaning: "to let go", meaningKh: "ចេញផ្សាយ", example: "They released the prisoner.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "relevant", meaning: "closely connected", meaningKh: "ពាក់ព័ន្ធ", example: "Your question is not relevant.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "reliable", meaning: "able to be trusted", meaningKh: "អាចទុកចិត្តបាន", example: "She's a reliable worker.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "relieve", meaning: "to make less painful", meaningKh: "បំបាត់ការឈឺចាប់", example: "This medicine relieves headaches.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "religion", meaning: "a system of belief", meaningKh: "សាសនា", example: "Respect every religion.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "reluctant", meaning: "unwilling", meaningKh: "ស្ទាក់ស្ទើរ", example: "I was reluctant to leave.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "remain", meaning: "to stay", meaningKh: "នៅសល់", example: "Please remain seated.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "remarkable", meaning: "very impressive", meaningKh: "គួរឱ្យកត់សម្គាល់", example: "It's a remarkable achievement.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "remind", meaning: "to cause to remember", meaningKh: "រំលឹក", example: "Remind me to call her.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "remote", meaning: "far away", meaningKh: "ដាច់ស្រយាល", example: "They live in a remote village.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "remove", meaning: "to take away", meaningKh: "យកចេញ", example: "Please remove your shoes.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "replace", meaning: "to put in place of another", meaningKh: "ជំនួស", example: "Replace the broken glass.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "represent", meaning: "to act for", meaningKh: "តំណាង", example: "She represents her country.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "require", meaning: "to need", meaningKh: "តម្រូវ", example: "This job requires patience.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "rescue", meaning: "to save from danger", meaningKh: "ជួយសង្គ្រោះ", example: "Firefighters rescued the cat.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "research", meaning: "careful study", meaningKh: "ការស្រាវជ្រាវ", example: "Scientists do research daily.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "resemble", meaning: "to be like", meaningKh: "ស្រដៀង", example: "She resembles her mother.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "reserve", meaning: "to keep for later", meaningKh: "កក់", example: "Please reserve a table for two.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "resign", meaning: "to give up a job", meaningKh: "លាឈប់", example: "He resigned from his position.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "resist", meaning: "to oppose", meaningKh: "តស៊ូ", example: "I can't resist chocolate.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "resolve", meaning: "to find a solution", meaningKh: "ដោះស្រាយ", example: "We resolved the issue quickly.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "resource", meaning: "a useful source of supply", meaningKh: "ធនធាន", example: "Water is a precious resource.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "respect", meaning: "to admire", meaningKh: "គោរព", example: "I respect my teachers.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "respond", meaning: "to reply", meaningKh: "ឆ្លើយតប", example: "She responded to the email.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "responsible", meaning: "in charge of; sensible", meaningKh: "ទទួលខុសត្រូវ", example: "Who is responsible for this?", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "restore", meaning: "to bring back", meaningKh: "ស្តារឡើងវិញ", example: "They restored the old building.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "restrict", meaning: "to limit", meaningKh: "កំណត់", example: "The road is restricted to buses.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "retain", meaning: "to keep", meaningKh: "រក្សា", example: "She retained her composure.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "retire", meaning: "to stop working", meaningKh: "ចូលនិវត្តន៍", example: "My father retired at 65.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "reveal", meaning: "to make known", meaningKh: "បង្ហាញ", example: "She revealed her secret.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "reverse", meaning: "to turn the opposite way", meaningKh: "ផ្ទុយ", example: "Reverse the car slowly.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "review", meaning: "to look at again", meaningKh: "ពិនិត្យឡើងវិញ", example: "Review your notes before the test.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "revise", meaning: "to change to improve", meaningKh: "កែលម្អ", example: "She revised her essay.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "reward", meaning: "something given for good work", meaningKh: "រង្វាន់", example: "He got a reward for honesty.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "risk", meaning: "the chance of harm", meaningKh: "ហានិភ័យ", example: "There's a risk of rain.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "ritual", meaning: "a religious or formal action", meaningKh: "ពិធីសាសនា", example: "Brushing teeth is a morning ritual.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "rival", meaning: "a competitor", meaningKh: "គូប្រកួត", example: "He is my main rival.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "role", meaning: "a part played", meaningKh: "តួនាទី", example: "She plays a key role in the team.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "routine", meaning: "a regular way of doing", meaningKh: "ទម្លាប់ប្រចាំថ្ងៃ", example: "Exercise is part of my routine.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "rural", meaning: "of the countryside", meaningKh: "ជនបទ", example: "They live in a rural area.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },

  // ===== S =====
  { word: "sacrifice", meaning: "to give up something important", meaningKh: "លះបង់", example: "Parents sacrifice for their children.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "salary", meaning: "regular pay for work", meaningKh: "ប្រាក់ខែ", example: "Her salary is paid monthly.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "satisfy", meaning: "to make happy", meaningKh: "បំពេញចិត្ត", example: "Her work satisfies her.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "scarce", meaning: "in short supply", meaningKh: "កម្រ", example: "Water is scarce in deserts.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "scholar", meaning: "a learned person", meaningKh: "អ្នកប្រាជ្ញ", example: "He is a famous scholar.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "scope", meaning: "the range of something", meaningKh: "វិសាលភាព", example: "That's outside the scope of the project.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "seek", meaning: "to try to find", meaningKh: "ស្វែងរក", example: "She seeks the truth.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "seize", meaning: "to take by force", meaningKh: "ចាប់យក", example: "He seized the opportunity.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "sensible", meaning: "showing good judgment", meaningKh: "មានវិចារណញ្ញាណ", example: "Wear sensible shoes.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "sensitive", meaning: "easily affected", meaningKh: "មានភាពរសើប", example: "She is sensitive to criticism.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "severe", meaning: "very serious", meaningKh: "ធ្ងន់ធ្ងរ", example: "She has a severe headache.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "shame", meaning: "feeling of having done wrong", meaningKh: "អាម៉ាស់", example: "He felt great shame.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "shift", meaning: "to move slightly", meaningKh: "ប្តូរ", example: "Shift the table to the left.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "shock", meaning: "a sudden upsetting event", meaningKh: "តក់ស្លុត", example: "The news came as a shock.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "shortage", meaning: "a lack of something", meaningKh: "ការខ្វះខាត", example: "There's a shortage of doctors.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "significant", meaning: "important", meaningKh: "សំខាន់", example: "It was a significant moment.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "similar", meaning: "alike", meaningKh: "ស្រដៀង", example: "These two cars are similar.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "sincere", meaning: "honest in feeling", meaningKh: "ស្មោះត្រង់", example: "Please accept my sincere apology.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "situation", meaning: "a set of circumstances", meaningKh: "ស្ថានភាព", example: "The situation is serious.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "skeptical", meaning: "doubting", meaningKh: "សង្ស័យ", example: "I'm skeptical of his story.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "society", meaning: "people living together", meaningKh: "សង្គម", example: "Society needs good leaders.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "sophisticated", meaning: "refined; complex", meaningKh: "ឧស្សាហ៍ឆ្លាតវៃ", example: "It's a sophisticated system.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "source", meaning: "place something comes from", meaningKh: "ប្រភព", example: "The sun is a source of energy.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "spare", meaning: "extra; available", meaningKh: "បន្ថែម", example: "Do you have a spare pen?", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "species", meaning: "a class of plants or animals", meaningKh: "ប្រភេទសត្វ", example: "Many species are endangered.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "specific", meaning: "particular; exact", meaningKh: "ជាក់លាក់", example: "Give me a specific example.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "stable", meaning: "not likely to change", meaningKh: "ស្ថិរភាព", example: "Her job is stable.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "stage", meaning: "a step in a process", meaningKh: "ដំណាក់កាល", example: "The project is in its final stage.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "standard", meaning: "a level of quality", meaningKh: "ស្តង់ដារ", example: "Our standards are high.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "status", meaning: "social position; condition", meaningKh: "ឋានៈ", example: "What is your marital status?", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "steady", meaning: "firm; constant", meaningKh: "ឋិតថេរ", example: "She has a steady job.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "stimulate", meaning: "to encourage activity", meaningKh: "ជំរុញ", example: "Coffee stimulates the brain.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "strain", meaning: "pressure or tension", meaningKh: "តានតឹង", example: "She felt the strain of work.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "strategy", meaning: "a plan to achieve a goal", meaningKh: "យុទ្ធសាស្ត្រ", example: "We need a new strategy.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "stress", meaning: "mental pressure", meaningKh: "ភាពតានតឹង", example: "Yoga reduces stress.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "stretch", meaning: "to extend", meaningKh: "ពង្រីក", example: "Stretch your arms above your head.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "strict", meaning: "demanding obedience", meaningKh: "តឹងរ៉ឹង", example: "Our teacher is strict.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "strive", meaning: "to try very hard", meaningKh: "ខិតខំ", example: "She strives for perfection.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "structure", meaning: "the way something is built", meaningKh: "រចនាសម្ព័ន្ធ", example: "The bridge has a strong structure.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "struggle", meaning: "to make great effort", meaningKh: "តស៊ូ", example: "She struggled to finish on time.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "substance", meaning: "matter; material", meaningKh: "សារធាតុ", example: "The bottle contains a strange substance.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "substitute", meaning: "to use in place of", meaningKh: "ជំនួស", example: "Substitute honey for sugar.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "succeed", meaning: "to achieve a goal", meaningKh: "ទទួលជោគជ័យ", example: "She succeeded in her dream.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "suffer", meaning: "to experience pain", meaningKh: "រងទុក្ខ", example: "He suffers from back pain.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "sufficient", meaning: "enough", meaningKh: "គ្រប់គ្រាន់", example: "We have sufficient food.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "suggest", meaning: "to propose", meaningKh: "ស្នើ", example: "I suggest we leave now.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "suitable", meaning: "appropriate", meaningKh: "សមរម្យ", example: "This is suitable for children.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "summarize", meaning: "to give a short version", meaningKh: "សង្ខេប", example: "Summarize the article.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "superior", meaning: "better than others", meaningKh: "ឧត្តម", example: "Their service is superior.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "supply", meaning: "to provide", meaningKh: "ផ្គត់ផ្គង់", example: "We supply schools with books.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "suppose", meaning: "to think likely", meaningKh: "សន្មត", example: "I suppose you're right.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "surround", meaning: "to be on all sides of", meaningKh: "ព័ទ្ធជុំវិញ", example: "Trees surround the house.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "survey", meaning: "to ask questions of many", meaningKh: "ការស្ទង់មតិ", example: "We did a survey on shopping habits.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "survive", meaning: "to continue to live", meaningKh: "រស់រាន", example: "Only three people survived.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "suspect", meaning: "to think probable", meaningKh: "សង្ស័យ", example: "I suspect he's lying.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "suspend", meaning: "to stop temporarily", meaningKh: "ផ្អាក", example: "Classes are suspended today.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "sustain", meaning: "to keep going", meaningKh: "ទ្រទ្រង់", example: "Trees sustain life on earth.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "swallow", meaning: "to make food go down the throat", meaningKh: "លេប", example: "Swallow the pill with water.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "sympathy", meaning: "sharing of feelings", meaningKh: "ការអាណិតអាសូរ", example: "She showed sympathy for the family.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "symptom", meaning: "a sign of illness", meaningKh: "រោគសញ្ញា", example: "A fever is a symptom of flu.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "system", meaning: "an organized set of methods", meaningKh: "ប្រព័ន្ធ", example: "We have a new computer system.", partOfSpeech: "noun", level: Level.INTERMEDIATE },

  // ===== T =====
  { word: "talent", meaning: "natural ability", meaningKh: "ទេពកោសល្យ", example: "She has a talent for music.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "technique", meaning: "a way of doing something", meaningKh: "បច្ចេកទេស", example: "She used a new painting technique.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "temporary", meaning: "lasting a short time", meaningKh: "បណ្តោះអាសន្ន", example: "He has a temporary job.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "tempt", meaning: "to attract", meaningKh: "បំបោល", example: "Sweets tempt children.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "tendency", meaning: "an inclination", meaningKh: "និន្នាការ", example: "She has a tendency to be late.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "tense", meaning: "anxious; tight", meaningKh: "តានតឹង", example: "She felt tense before the test.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "terrible", meaning: "very bad", meaningKh: "ខ្លាំងណាស់", example: "I had a terrible day.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "territory", meaning: "an area of land", meaningKh: "ទឹកដី", example: "This is enemy territory.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "threat", meaning: "danger", meaningKh: "ការគំរាមកំហែង", example: "Pollution is a threat to health.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "thrive", meaning: "to grow strong", meaningKh: "រីកចម្រើន", example: "Plants thrive in sunlight.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "tolerate", meaning: "to put up with", meaningKh: "អត់ឱន", example: "I won't tolerate rudeness.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "tough", meaning: "strong; difficult", meaningKh: "រឹង", example: "It was a tough decision.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "trace", meaning: "a small remaining sign", meaningKh: "ដាន", example: "There was no trace of the thief.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "transfer", meaning: "to move from one place to another", meaningKh: "ផ្ទេរ", example: "She transferred to a new school.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "transform", meaning: "to change completely", meaningKh: "ប្តូររូបរាង", example: "Technology transformed our lives.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "translate", meaning: "to change from one language to another", meaningKh: "បកប្រែ", example: "Can you translate this letter?", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "transport", meaning: "to carry from one place to another", meaningKh: "ដឹកជញ្ជូន", example: "Trucks transport goods daily.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "trend", meaning: "a general direction", meaningKh: "និន្នាការ", example: "Fashion trends change quickly.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "trial", meaning: "a test; a court case", meaningKh: "ការសាកល្បង", example: "It's a free three-day trial.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "trigger", meaning: "to cause to happen", meaningKh: "បង្ករ", example: "The noise triggered the alarm.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "trust", meaning: "to believe in", meaningKh: "ទុកចិត្ត", example: "I trust my friends.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "typical", meaning: "having the usual qualities", meaningKh: "ធម្មតា", example: "It's a typical Sunday morning.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },

  // ===== U =====
  { word: "uncertain", meaning: "not sure", meaningKh: "មិនច្បាស់", example: "The future is uncertain.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "undergo", meaning: "to experience", meaningKh: "ឆ្លងកាត់", example: "She underwent surgery.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "undertake", meaning: "to take on a task", meaningKh: "ទទួលយក", example: "He will undertake the project.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "unfortunate", meaning: "unlucky", meaningKh: "សំណាងអាក្រក់", example: "It was an unfortunate accident.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "universal", meaning: "applying to everyone", meaningKh: "សកល", example: "Music is a universal language.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "unless", meaning: "except if", meaningKh: "លុះត្រាតែ", example: "I won't go unless you come.", partOfSpeech: "conjunction", level: Level.INTERMEDIATE },
  { word: "unusual", meaning: "not common", meaningKh: "មិនធម្មតា", example: "She has an unusual name.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "update", meaning: "to bring up to date", meaningKh: "ធ្វើឱ្យទាន់សម័យ", example: "Please update your records.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "upset", meaning: "to make unhappy", meaningKh: "ខូចចិត្ត", example: "Don't upset her.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "urgent", meaning: "requiring immediate action", meaningKh: "បន្ទាន់", example: "This is an urgent message.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "utilize", meaning: "to make use of", meaningKh: "ប្រើប្រាស់", example: "Utilize your time wisely.", partOfSpeech: "verb", level: Level.INTERMEDIATE },

  // ===== V =====
  { word: "valid", meaning: "acceptable; legally binding", meaningKh: "មានសុពលភាព", example: "Your passport is still valid.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "valuable", meaning: "worth a lot", meaningKh: "មានតម្លៃ", example: "Her advice is valuable.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "vary", meaning: "to differ", meaningKh: "ប្រែប្រួល", example: "Prices vary by store.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "vast", meaning: "very large", meaningKh: "ទូលំទូលាយ", example: "She has vast knowledge.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "venue", meaning: "a place for an event", meaningKh: "ទីកន្លែងរៀបចំ", example: "The venue is downtown.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "version", meaning: "a form of something", meaningKh: "កំណែ", example: "This is the latest version.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "violate", meaning: "to break a rule", meaningKh: "បំពាន", example: "Don't violate the law.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "virtual", meaning: "almost real; on a computer", meaningKh: "និម្មិត", example: "We had a virtual meeting.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "visible", meaning: "able to be seen", meaningKh: "មើលឃើញ", example: "The stars are visible tonight.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "vital", meaning: "essential", meaningKh: "សំខាន់បំផុត", example: "Water is vital for life.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "vivid", meaning: "bright; clear", meaningKh: "ច្បាស់ស្រឡះ", example: "She has a vivid memory.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "voluntary", meaning: "done by choice", meaningKh: "ស្ម័គ្រចិត្ត", example: "This is voluntary work.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "vote", meaning: "to choose by ballot", meaningKh: "បោះឆ្នោត", example: "Citizens vote in elections.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "vulnerable", meaning: "easily harmed", meaningKh: "ងាយរងគ្រោះ", example: "Children are vulnerable.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },

  // ===== W =====
  { word: "wander", meaning: "to walk without aim", meaningKh: "ដើរយ៉ាងគ្មានទិសដៅ", example: "They wandered through the city.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "welfare", meaning: "well-being", meaningKh: "សុខុមាលភាព", example: "We care about your welfare.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "whisper", meaning: "to speak very quietly", meaningKh: "ខ្សឹប", example: "She whispered the answer.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "widespread", meaning: "over a large area", meaningKh: "រាលដាល", example: "There is widespread support.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "willing", meaning: "ready to help", meaningKh: "សុខចិត្ត", example: "She is willing to help.", partOfSpeech: "adjective", level: Level.INTERMEDIATE },
  { word: "withdraw", meaning: "to take back", meaningKh: "ដកចេញ", example: "He withdrew money from the bank.", partOfSpeech: "verb", level: Level.INTERMEDIATE },
  { word: "witness", meaning: "a person who saw something", meaningKh: "សាក្សី", example: "There were no witnesses to the crime.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "worth", meaning: "value", meaningKh: "តម្លៃ", example: "This book is worth reading.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
];
