import { Level } from "@prisma/client";
import type { VocabEntry } from "./types";

export const jobsVocab: VocabEntry[] = [
  { word: "waiter", meaning: "a man who serves food in a restaurant", meaningKh: "បុរសជូនអាហារ", example: "The waiter took our order.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "waitress", meaning: "a woman who serves food in a restaurant", meaningKh: "ស្ត្រីជូនអាហារ", example: "The waitress was very friendly.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "chef", meaning: "a professional cook in a restaurant or hotel", meaningKh: "ចុងធ្វើម្ហូប", example: "She works as a chef.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "butcher", meaning: "a person who cuts and sells meat", meaningKh: "អ្នកចិញ្ចាត់សាច់", example: "Buy beef from the butcher.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "farmer", meaning: "a person who grows crops or raises animals", meaningKh: "កសិករ", example: "The farmer grows rice.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "scientist", meaning: "a person who studies science", meaningKh: "អ្នកវិទ្យាសាស្ត្រ", example: "Scientists run experiments.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "hairdresser", meaning: "a person who cuts and styles hair (also called a stylist)", meaningKh: "ជាងកាត់សក់", example: "I see my hairdresser every month.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "gardener", meaning: "a person who takes care of gardens and plants", meaningKh: "អ្នកថែសួន", example: "The gardener trims the hedges.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "cleaner", meaning: "a person who cleans buildings (also called a janitor)", meaningKh: "អ្នកសម្អាត", example: "The cleaner comes at night.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "train driver", meaning: "a person who drives a train", meaningKh: "អ្នកបើករថភ្លើង", example: "The train driver stopped at the station.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "taxi driver", meaning: "a person who drives a taxi for passengers", meaningKh: "អ្នកបើកតាក់ស៊ី", example: "The taxi driver knew a shortcut.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "librarian", meaning: "a person who works in a library", meaningKh: "បណ្ណារក្ស", example: "Ask the librarian for help.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "lawyer", meaning: "a person trained to advise on legal matters", meaningKh: "មេធាវី", example: "She hired a lawyer.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "teacher", meaning: "a person who teaches students", meaningKh: "គ្រូ", example: "The teacher explained the lesson.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "judge", meaning: "an official who decides cases in court", meaningKh: "ចុងតុលាការ", example: "The judge listened carefully.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "police officer", meaning: "a member of the police force", meaningKh: "ប៉ូលីស", example: "A police officer directed traffic.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "firefighter", meaning: "a person whose job is to put out fires", meaningKh: "អ្នកពន្លត់អគ្គិភ័យ", example: "Firefighters arrived quickly.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "security guard", meaning: "a person who protects a building or property", meaningKh: "អ្នករក្សាសន្តិភាព", example: "The security guard checked IDs.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "driver", meaning: "a person who drives a vehicle for work", meaningKh: "អ្នកបើកបរ", example: "The driver delivered the package.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "electrician", meaning: "a person who installs and repairs electrical systems", meaningKh: "អ្នកអគ្គិសនី", example: "Call an electrician for the wiring.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "construction worker", meaning: "a person who builds or repairs buildings", meaningKh: "កម្មករសំណង់", example: "Construction workers wear hard hats.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "plumber", meaning: "a person who installs and repairs water pipes", meaningKh: "អ្នកជួសជុលបំពាក់ទឹក", example: "The plumber fixed the leak.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "engineer", meaning: "a person who designs or builds machines, roads, or systems", meaningKh: "វិស្វករ", example: "She is a software engineer.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "architect", meaning: "a person who designs buildings", meaningKh: "ស្ថាបត្យករ", example: "The architect drew the plans.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "mechanic", meaning: "a person who repairs vehicles or machines", meaningKh: "ជាងជួសជុល", example: "The mechanic checked the engine.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "businessman", meaning: "a man who works in business", meaningKh: "អ្នកជំនួញបុរស", example: "He is a successful businessman.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "businesswoman", meaning: "a woman who works in business", meaningKh: "អ្នកជំនួញស្ត្រី", example: "She is a businesswoman.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "sales assistant", meaning: "a person who helps customers in a shop", meaningKh: "បុគ្គលិកលក់", example: "The sales assistant showed the shoes.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "receptionist", meaning: "a person who greets visitors at an office or hotel", meaningKh: "បុគ្គលិកទទួល", example: "The receptionist answered the phone.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "personal assistant", meaning: "a person who helps a manager with daily tasks (PA)", meaningKh: "អ្នកជំនួយការផ្ទាល់", example: "Her PA manages her calendar.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "surgeon", meaning: "a doctor who performs operations", meaningKh: "គ្រូពេទ្យវះកាត់", example: "The surgeon operated for hours.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "doctor", meaning: "a person trained to treat sick people", meaningKh: "គ្រូពេទ្យ", example: "See a doctor if you feel ill.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "nurse", meaning: "a person who cares for patients in a hospital", meaningKh: "គិលានុបដ្ឋាយិកា", example: "The nurse checked my temperature.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "dentist", meaning: "a doctor who treats teeth", meaningKh: "គ្រូពេទ្យធ្មេញ", example: "Visit the dentist twice a year.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "paramedic", meaning: "a person trained to give emergency medical care", meaningKh: "បុគ្គលិកជំនួយបន្ទាន់", example: "Paramedics arrived at the scene.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "psychologist", meaning: "a person who studies the mind and behavior", meaningKh: "អ្នកចិត្តវិទ្យា", example: "She talked to a psychologist.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "child-care provider", meaning: "a person who looks after children while parents work", meaningKh: "អ្នកថែកុមារ", example: "The child-care provider reads stories.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "vet", meaning: "a doctor for animals (veterinarian)", meaningKh: "ពេទ្យសត្វ", example: "Take the dog to the vet.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "pilot", meaning: "a person who flies an aircraft", meaningKh: "អ្នកបើកយន្តហោះ", example: "The pilot announced landing.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "flight attendant", meaning: "a person who serves passengers on a plane", meaningKh: "បុគ្គលិកជើងអាកាស", example: "The flight attendant served drinks.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "travel agent", meaning: "a person who arranges trips and tickets for travelers", meaningKh: "ភ្នាក់ងារទេសចរណ៍", example: "Book flights through a travel agent.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "tour guide", meaning: "a person who shows tourists places of interest", meaningKh: "មគ្គុទេសចរណ៍", example: "Our tour guide explained the temple.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "journalist", meaning: "a person who writes news stories", meaningKh: "អ្នកសារព័ត៌មាន", example: "The journalist interviewed the mayor.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "writer", meaning: "a person who writes books, articles, or stories", meaningKh: "អ្នកនិពន្ធ", example: "She is a famous writer.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "designer", meaning: "a person who plans how things look or work", meaningKh: "អ្នករចនា", example: "He works as a graphic designer.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "photographer", meaning: "a person who takes photographs professionally", meaningKh: "អ្នកថតរូប", example: "The photographer shot the wedding.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "actor", meaning: "a person who performs in plays, films, or TV", meaningKh: "តារាសម្តែង", example: "He became a famous actor.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "artist", meaning: "a person who creates art", meaningKh: "វិចិត្រករ", example: "The artist sold her paintings.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "musician", meaning: "a person who plays music professionally", meaningKh: "តន្ត្រភិវូរ", example: "She is a talented musician.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "fashion designer", meaning: "a person who designs clothing", meaningKh: "អ្នករចនាម៉ូដ", example: "The fashion designer showed a new collection.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
];
