import { Level } from "@prisma/client";
import type { VocabEntry } from "./types";

export const kitchenUtensilsVocab: VocabEntry[] = [
  { word: "wok", meaning: "a deep round pan used in Asian cooking", meaningKh: "ឆ្នាំងគោម", example: "Stir-fry the vegetables in a wok.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "pot", meaning: "a round, deep cooking container with a handle", meaningKh: "ឆ្នាំង", example: "Boil the rice in a pot.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "saucepan", meaning: "a small, deep pan with a long handle and lid", meaningKh: "ឆ្នាំងតូច", example: "Heat the milk in a saucepan.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "lid", meaning: "a cover for a pot or container", meaningKh: "គម្របឆ្នាំង", example: "Put the lid on the pot to keep it warm.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "frying pan", meaning: "a shallow pan for frying food (also called a skillet)", meaningKh: "ខ្ទះ", example: "Fry the eggs in a frying pan.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "roasting pan", meaning: "a large, deep pan used to roast meat in an oven", meaningKh: "ខ្ទះអាំង", example: "Place the chicken in the roasting pan.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "roaster", meaning: "a pan or rack used for roasting meat", meaningKh: "ឧបករណ៍អាំង", example: "Slide the roaster into the oven.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "double boiler", meaning: "two stacked pots used to heat food gently with steam", meaningKh: "ឆ្នាំងពីរជាន់", example: "Melt the chocolate in a double boiler.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "pressure cooker", meaning: "a sealed pot that cooks food quickly using steam pressure", meaningKh: "ឆ្នាំងសម្ពាធ", example: "Beans cook fast in a pressure cooker.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "colander", meaning: "a bowl with holes for draining liquid from food", meaningKh: "ចានសម្រូប", example: "Drain the pasta in a colander.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "casserole dish", meaning: "a deep oven dish for baking food", meaningKh: "ចានដុតនំ", example: "Bake the lasagna in a casserole dish.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "cake pan", meaning: "a round pan used for baking cakes", meaningKh: "ខ្ទះធ្វើនំ", example: "Pour the batter into the cake pan.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "pie plate", meaning: "a shallow round dish for baking pies", meaningKh: "ចានធ្វើនំខូឃី", example: "Roll the dough into the pie plate.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "cookie sheet", meaning: "a flat metal tray for baking cookies", meaningKh: "ថាសដុតនំខូឃី", example: "Place the cookies on the cookie sheet.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "mixing bowl", meaning: "a large bowl used for mixing ingredients", meaningKh: "ចានធំសម្រាប់លាយ", example: "Combine the flour and sugar in a mixing bowl.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "rolling pin", meaning: "a cylinder used to flatten dough", meaningKh: "ដំបងគៀបម្សៅ", example: "Roll the dough with a rolling pin.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "measuring cup", meaning: "a cup marked with units to measure ingredients", meaningKh: "ពែងវាស់", example: "Use a measuring cup for the rice.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "measuring spoon", meaning: "a small spoon for measuring ingredients", meaningKh: "ស្លាបព្រាវាស់", example: "Add a measuring spoon of salt.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "coffeemaker", meaning: "a machine that brews coffee", meaningKh: "ម៉ាស៊ីនធ្វើកាហ្វេ", example: "Set the coffeemaker for 6 a.m.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "coffee grinder", meaning: "a machine that grinds coffee beans", meaningKh: "ម៉ាស៊ីនកិនកាហ្វេ", example: "Grind the beans in the coffee grinder.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "tea kettle", meaning: "a kettle used to boil water for tea", meaningKh: "កែបឺតែ", example: "Put the tea kettle on the stove.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "toaster oven", meaning: "a small oven used for toasting and baking", meaningKh: "ឡដុតនំតូច", example: "Heat the bread in the toaster oven.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "electric mixer", meaning: "an electric appliance that mixes ingredients", meaningKh: "ម៉ាស៊ីនលាយអគ្គិសនី", example: "Beat the cream with an electric mixer.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "food processor", meaning: "a machine that chops and blends food", meaningKh: "ម៉ាស៊ីនកំទេចអាហារ", example: "Chop onions in the food processor.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "electric frying pan", meaning: "a frying pan with its own heating element", meaningKh: "ខ្ទះអគ្គិសនី", example: "Cook the eggs in an electric frying pan.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "waffle iron", meaning: "an appliance that cooks waffles", meaningKh: "ម៉ាស៊ីនធ្វើវ៉ាហ្វេល", example: "Pour the batter into the waffle iron.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "electric griddle", meaning: "a flat heated surface for cooking pancakes and more", meaningKh: "ផ្ទាំងចម្អិនអគ្គិសនី", example: "Make pancakes on the electric griddle.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "popcorn maker", meaning: "a machine that pops popcorn", meaningKh: "ម៉ាស៊ីនធ្វើពោត", example: "Use the popcorn maker for movie night.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "blender", meaning: "an electric machine that blends or purees food", meaningKh: "ម៉ាស៊ីនកិន", example: "Make a smoothie in the blender.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "grater", meaning: "a tool with sharp holes for shredding food", meaningKh: "ឧបករណ៍កិន", example: "Grate the cheese with a grater.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "egg beater", meaning: "a tool used to mix eggs by hand", meaningKh: "ឧបករណ៍វាយពង", example: "Whisk the eggs with an egg beater.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "ladle", meaning: "a deep, long-handled spoon for serving soup", meaningKh: "ស្លាបព្រាស៊ុបធំ", example: "Serve the soup with a ladle.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "ice cream scoop", meaning: "a rounded scoop for serving ice cream", meaningKh: "ឧបករណ៍ដួងការ៉េម", example: "Use an ice cream scoop for neat scoops.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "cookie cutter", meaning: "a shape used to cut cookies from dough", meaningKh: "ឧបករណ៍កាត់នំខូឃី", example: "Press the cookie cutter into the dough.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "strainer", meaning: "a tool with a mesh to drain liquid from food", meaningKh: "ឧបករណ៍ត្រង", example: "Pour the tea through a strainer.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "garlic press", meaning: "a tool that crushes garlic cloves", meaningKh: "ឧបករណ៍កិនខ្ទឹមស", example: "Mince a clove in the garlic press.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "bottle opener", meaning: "a tool used to remove caps from bottles", meaningKh: "ឧបករណ៍បើកដប", example: "Open the soda with a bottle opener.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "can opener", meaning: "a tool used to open metal cans", meaningKh: "ឧបករណ៍បើកកំប៉ុង", example: "Use a can opener for the soup can.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "whisk", meaning: "a kitchen tool for beating or mixing", meaningKh: "ដំបងវាយ", example: "Mix the eggs with a whisk.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "vegetable peeler", meaning: "a tool that removes the skin from vegetables", meaningKh: "ឧបករណ៍ចិតស្បែកបន្លែ", example: "Peel the potatoes with a vegetable peeler.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "kitchen knife", meaning: "a sharp blade used for cutting food", meaningKh: "កាំបិតផ្ទះបាយ", example: "Slice the bread with a kitchen knife.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "spatula", meaning: "a flat tool used to lift and flip food", meaningKh: "ស្លាបព្រាមាត់ស្តើង", example: "Flip the pancake with a spatula.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "paring knife", meaning: "a small knife used for peeling fruit and small jobs", meaningKh: "កាំបិតតូចចិតផ្លែឈើ", example: "Peel the apple with a paring knife.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
];
