import { Level } from "@prisma/client";
import type { VocabEntry } from "./types";

export const numbersCardinalVocab: VocabEntry[] = [
  { word: "four", meaning: "the number 4", meaningKh: "បួន", example: "I have four sisters.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "five", meaning: "the number 5", meaningKh: "ប្រាំ", example: "Give me five minutes.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "six", meaning: "the number 6", meaningKh: "ប្រាំមួយ", example: "School starts at six o'clock.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "seven", meaning: "the number 7", meaningKh: "ប្រាំពីរ", example: "There are seven days in a week.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "eight", meaning: "the number 8", meaningKh: "ប្រាំបី", example: "The cake has eight slices.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "nine", meaning: "the number 9", meaningKh: "ប្រាំបួន", example: "She is nine years old.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "ten", meaning: "the number 10", meaningKh: "ដប់", example: "Count to ten.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "eleven", meaning: "the number 11", meaningKh: "ដប់មួយ", example: "The store opens at eleven.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "twelve", meaning: "the number 12", meaningKh: "ដប់ពីរ", example: "Twelve eggs make a dozen.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "thirteen", meaning: "the number 13", meaningKh: "ដប់បី", example: "He turned thirteen last month.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "fourteen", meaning: "the number 14", meaningKh: "ដប់បួន", example: "Fourteen students are absent.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "fifteen", meaning: "the number 15", meaningKh: "ដប់ប្រាំ", example: "Wait fifteen minutes.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "sixteen", meaning: "the number 16", meaningKh: "ដប់ប្រាំមួយ", example: "She is sixteen years old.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "seventeen", meaning: "the number 17", meaningKh: "ដប់ប្រាំពីរ", example: "There were seventeen guests.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "eighteen", meaning: "the number 18", meaningKh: "ដប់ប្រាំបី", example: "You can vote at eighteen.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "nineteen", meaning: "the number 19", meaningKh: "ដប់ប្រាំបួន", example: "Nineteen people came to the party.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "twenty", meaning: "the number 20", meaningKh: "ម្ភៃ", example: "Twenty students passed the test.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "twenty-one", meaning: "the number 21", meaningKh: "ម្ភៃមួយ", example: "My brother just turned twenty-one.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "twenty-two", meaning: "the number 22", meaningKh: "ម្ភៃពីរ", example: "Twenty-two players are on the field.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "thirty", meaning: "the number 30", meaningKh: "សាមសិប", example: "Thirty minutes left.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "forty", meaning: "the number 40", meaningKh: "សែសិប", example: "She is forty years old.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "fifty", meaning: "the number 50", meaningKh: "ហាសិប", example: "Fifty dollars, please.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "sixty", meaning: "the number 60", meaningKh: "ហុកសិប", example: "There are sixty seconds in a minute.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "seventy", meaning: "the number 70", meaningKh: "ចិតសិប", example: "Grandpa is seventy this year.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "eighty", meaning: "the number 80", meaningKh: "ប៉ែតសិប", example: "Eighty percent agreed.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "ninety", meaning: "the number 90", meaningKh: "កៅសិប", example: "She lived to be ninety.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "one hundred", meaning: "the number 100", meaningKh: "មួយរយ", example: "Count from one to one hundred.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "one thousand", meaning: "the number 1,000", meaningKh: "មួយពាន់", example: "The shirt costs one thousand riel.", partOfSpeech: "number", level: Level.BEGINNER },
  { word: "ten thousand", meaning: "the number 10,000", meaningKh: "មួយម៉ឺន", example: "Ten thousand people attended.", partOfSpeech: "number", level: Level.INTERMEDIATE },
  { word: "one hundred thousand", meaning: "the number 100,000", meaningKh: "មួយសែន", example: "She has one hundred thousand followers.", partOfSpeech: "number", level: Level.INTERMEDIATE },
  { word: "one million", meaning: "the number 1,000,000", meaningKh: "មួយលាន", example: "The lottery prize is one million dollars.", partOfSpeech: "number", level: Level.BEGINNER },
];
