import { Level } from "@prisma/client";
import type { VocabEntry } from "./types";

export const personalCareVocab: VocabEntry[] = [
  { word: "comb", meaning: "a tool with teeth for arranging hair", meaningKh: "ព្រះ", example: "Run a comb through your hair.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "hair brush", meaning: "a brush for grooming hair", meaningKh: "ច្រាសសក់", example: "Brush your hair with a hair brush.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "razor", meaning: "a tool with a blade for shaving hair", meaningKh: "កាំបិតកោរពុំ", example: "He uses a razor every morning.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "razor blades", meaning: "replaceable blades for a razor", meaningKh: "កាំបិតកោរពុំ", example: "Change the razor blades when dull.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "electric razor", meaning: "a powered razor (also called an electric shaver)", meaningKh: "ម៉ាស៊ីនកោរពុំ", example: "Charge the electric razor overnight.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "styptic pencil", meaning: "a stick that stops bleeding from small cuts", meaningKh: "ដំបងឈប់ឈាម", example: "Use a styptic pencil on nicks.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "shower cap", meaning: "a cap worn to keep hair dry in the shower", meaningKh: "មួកងូតទឹក", example: "Put on a shower cap to protect your hair.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "nail file", meaning: "a tool for shaping fingernails", meaningKh: "ញីក្រចក", example: "File your nails with a nail file.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "emery board", meaning: "a cardboard nail file coated with emery", meaningKh: "ក្តារញីក្រចក", example: "Smooth edges with an emery board.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "nail clipper", meaning: "a tool for cutting fingernails and toenails", meaningKh: "កន្ត្រាក្រចក", example: "Trim nails with a nail clipper.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "nail brush", meaning: "a small brush for cleaning under nails", meaningKh: "ច្រាសដុសក្រចក", example: "Scrub with a nail brush and soap.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "scissors", meaning: "a tool with two blades for cutting", meaningKh: "កន្ត្រាក", example: "Use scissors to trim the thread.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "tweezers", meaning: "a small tool for plucking hairs or picking up objects", meaningKh: "ដង្កីបូត", example: "Pluck eyebrows with tweezers.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "bobby pins", meaning: "flat hairpins that hold hair in place", meaningKh: "ម្ជុលសក់", example: "Secure the bun with bobby pins.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "hair clips", meaning: "clips used to hold sections of hair", meaningKh: "កញ្ចក់សក់", example: "She used hair clips while styling.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "barrettes", meaning: "decorative clips that fasten hair", meaningKh: "កញ្ចក់តុក្កវ៉ា", example: "The girl wore colorful barrettes.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "shampoo", meaning: "liquid soap for washing hair", meaningKh: "សាប៊ូកក់សក់", example: "Lather your hair with shampoo.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "conditioner", meaning: "a product that softens hair after shampoo (also called a rinse)", meaningKh: "ក្រែមសក់", example: "Apply conditioner and rinse well.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "hairspray", meaning: "a spray that holds hair in place", meaningKh: "ស្ព្រេយ៍សក់", example: "A little hairspray keeps the style.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "toothpaste", meaning: "paste used with a toothbrush to clean teeth", meaningKh: "ថ្នាំម្រាម", example: "Squeeze toothpaste onto the brush.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "mouthwash", meaning: "a liquid rinse for freshening the mouth", meaningKh: "ទឹកអំបាប់មាត់", example: "Rinse with mouthwash after brushing.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "dental floss", meaning: "thin string for cleaning between teeth", meaningKh: "ខ្សែសម្អាប់ធ្មេញ", example: "Floss between your teeth daily.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "shaving cream", meaning: "cream applied before shaving", meaningKh: "ក្រែមកោរពុំ", example: "Spread shaving cream on your face.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "after shave lotion", meaning: "lotion applied to skin after shaving", meaningKh: "ឡូស្យុងបន្ទាប់កោរ", example: "Pat on after shave lotion.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "deodorant", meaning: "a product that reduces body odor", meaningKh: "បំបាត់ក្លិន", example: "Apply deodorant in the morning.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "powder", meaning: "fine dry particles used on the skin", meaningKh: "ក្រម៉ៅ", example: "Dust powder on after a shower.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "hand lotion", meaning: "lotion for moisturizing hands", meaningKh: "ឡូស្យុងដៃ", example: "Keep hand lotion by the sink.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "perfume", meaning: "a fragrant liquid worn on the skin (cologne is a men's version)", meaningKh: "ទឹរក្រអើ", example: "She wore a light perfume.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "shoe polish", meaning: "a substance for shining leather shoes", meaningKh: "ថ្នាំលាបស្បែកជើង", example: "Buff the shoes with shoe polish.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "nail polish", meaning: "colored lacquer for fingernails or toenails", meaningKh: "ថ្នាំលាបក្រចក", example: "Let the nail polish dry.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "nail polish remover", meaning: "a liquid that removes nail polish", meaningKh: "ទឹកលាងថ្នាំក្រចក", example: "Soak cotton in nail polish remover.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "foundation", meaning: "makeup applied as a base on the face (also called base)", meaningKh: "មូលដ្ឋានមេឃ", example: "Blend foundation evenly.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "blush", meaning: "colored makeup for the cheeks (also called rouge)", meaningKh: "ថ្នាំលាបផ្សែង", example: "Add a touch of blush.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "lipstick", meaning: "colored cosmetic for the lips", meaningKh: "ថ្នាំលាបបបូរ", example: "She chose a red lipstick.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "eye shadow", meaning: "colored makeup for the eyelids", meaningKh: "ថ្នាំលាបភ្នែក", example: "Apply eye shadow lightly.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "eye liner", meaning: "makeup drawn along the edge of the eyes", meaningKh: "ខ្សែគូរភ្នែក", example: "Draw a thin line with eye liner.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "mascara", meaning: "makeup for darkening and thickening eyelashes", meaningKh: "ថ្នាំលាបរោមភ្នែក", example: "Apply mascara to upper lashes.", partOfSpeech: "noun", level: Level.BEGINNER },
];
