import { Level } from "@prisma/client";
import type { VocabEntry } from "./types";

export const toolsVocab: VocabEntry[] = [
  { word: "hammer", meaning: "a tool with a heavy head used to drive nails", meaningKh: "ញញួរ", example: "Hit the nail with the hammer.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "screwdriver", meaning: "a tool with a handle for turning screws", meaningKh: "ដែកគួច", example: "Use a screwdriver to tighten the screw.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "Phillips screwdriver", meaning: "a screwdriver with a cross-shaped tip", meaningKh: "ដែកគួចបូក", example: "You need a Phillips screwdriver for that screw.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "wrench", meaning: "a tool used to grip and turn nuts and bolts", meaningKh: "កូនសោចេក", example: "Loosen the bolt with a wrench.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "pliers", meaning: "a tool with jaws for holding or bending small objects", meaningKh: "ដង្កាប់", example: "Pull the nail out with pliers.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "hacksaw", meaning: "a small saw used to cut metal", meaningKh: "រណារកាត់ដែក", example: "Cut the pipe with a hacksaw.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "hatchet", meaning: "a small axe for chopping wood", meaningKh: "ពូថៅតូច", example: "Split the kindling with a hatchet.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "monkey wrench", meaning: "an adjustable wrench for pipes and nuts", meaningKh: "កូនសោចេកអាចលៃ", example: "Use a monkey wrench on the leaking pipe.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "saw", meaning: "a tool with a long, toothed blade for cutting wood", meaningKh: "រណារ", example: "Cut the board with a saw.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "hand drill", meaning: "a tool that drills holes by turning a handle", meaningKh: "ឧបករណ៍ខួងដៃ", example: "Make the hole with a hand drill.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "brace", meaning: "a hand tool used to hold and turn a drill bit", meaningKh: "ឧបករណ៍កាន់ខួង", example: "Steady the brace as you drill.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "chisel", meaning: "a tool with a sharp edge for shaping wood or stone", meaningKh: "ដែកដាប់", example: "Carve the wood with a chisel.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "scraper", meaning: "a tool with a flat blade used to scrape surfaces", meaningKh: "ឧបករណ៍កោស", example: "Remove old paint with a scraper.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "vise", meaning: "a clamp that holds something firmly while you work on it", meaningKh: "ឧបករណ៍គៀប", example: "Lock the wood in the vise.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "electric drill", meaning: "a powered tool that drills holes quickly", meaningKh: "ម៉ាស៊ីនខួងអគ្គិសនី", example: "Drill the holes with an electric drill.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "drill bit", meaning: "the metal part of a drill that makes the hole", meaningKh: "ដង្កៀបខួង", example: "Use a larger drill bit for the screws.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "power saw", meaning: "an electric saw that cuts quickly", meaningKh: "រណារអគ្គិសនី", example: "Cut the planks with a power saw.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "level", meaning: "a tool that shows if a surface is flat or horizontal", meaningKh: "ឧបករណ៍វាស់ត្រង់", example: "Check the shelf with a level.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "plane", meaning: "a tool that shaves thin layers from wood", meaningKh: "ឧបករណ៍ឆ្នូត", example: "Smooth the wood with a plane.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "toolbox", meaning: "a box for storing and carrying tools", meaningKh: "ប្រអប់ឧបករណ៍", example: "Keep all your tools in the toolbox.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "paint pan", meaning: "a shallow tray used to hold paint for a roller", meaningKh: "ខ្ទះដាក់ថ្នាំលាប", example: "Pour the paint into the paint pan.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "paint roller", meaning: "a roller for applying paint to walls", meaningKh: "ស៊ីឡាំងលាបថ្នាំ", example: "Roll the paint on with a paint roller.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "paintbrush", meaning: "a brush used for painting", meaningKh: "ច្រាសលាបថ្នាំ", example: "Dip the paintbrush in the can.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "paint", meaning: "a colored liquid used to cover walls and surfaces", meaningKh: "ថ្នាំលាប", example: "Buy a can of white paint.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "paint thinner", meaning: "a liquid used to thin paint or clean brushes", meaningKh: "ទឹករំលាយថ្នាំលាប", example: "Clean the brushes with paint thinner.", partOfSpeech: "noun", level: Level.ADVANCED },
  { word: "sandpaper", meaning: "rough paper used to smooth surfaces", meaningKh: "ក្រដាសខាត់", example: "Sand the table with sandpaper.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "wire", meaning: "a thin strand of metal used for electrical or other connections", meaningKh: "ខ្សែភ្លើង", example: "Cut the wire to length.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "nail", meaning: "a thin metal spike hammered into wood to join things", meaningKh: "ដែក​គោល", example: "Drive the nail straight in.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "screw", meaning: "a metal fastener with grooves that is turned in", meaningKh: "វីស", example: "Tighten the screw with the screwdriver.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "washer", meaning: "a flat ring placed under a nut or bolt head", meaningKh: "កង់រ៉ុង", example: "Put a washer under the bolt.", partOfSpeech: "noun", level: Level.INTERMEDIATE },
  { word: "bolt", meaning: "a metal pin that fastens things together with a nut", meaningKh: "បូឡុង", example: "Tighten the bolt with a wrench.", partOfSpeech: "noun", level: Level.BEGINNER },
  { word: "nut", meaning: "a small metal piece that screws onto a bolt", meaningKh: "ត្នោតបូឡុង", example: "Spin the nut onto the bolt.", partOfSpeech: "noun", level: Level.BEGINNER },
];
